import scopeDrift from './editorial/aug18-scope-drift.json';
import ownerAvailability from './editorial/aug18-owner-availability.json';
import queueEvidence from './editorial/aug18-queue-evidence.json';
import articleConflict from './editorial/aug18-article-conflict.json';
import handoffAcceptance from './editorial/aug18-handoff-acceptance.json';
import updatePromises from './editorial/aug18-update-promises.json';
import searchIntent from './editorial/aug18-search-intent.json';
import privacyRedaction from './editorial/aug18-privacy-redaction.json';
import exceptionRouting from './editorial/aug18-exception-routing.json';
import reviewSampling from './editorial/aug18-review-sampling.json';

type RepairSeed = { slug: string; title: string; excerpt: string; published: string; sourceDate: string; question: string; focus: string; finding: string; limitation: string; methodology: string; analysis: string; evidenceNotes: string; conclusion: string; sources: { name: string; url: string; note: string }[]; related: string[] };
type RepairPost = { slug: string; title: string; excerpt: string; published: string; sourceDate: string; keyStats: { value: string; label: string }[]; body: string[]; sources: RepairSeed['sources']; related: string[] };

const bodyFor = (s: RepairSeed): string[] => [
  `Research question: ${s.question} The question is specific to outsourced helpdesk work because a frontline specialist must keep a request moving while respecting the customer's systems, approval limits, and accountable owner. It does not ask whether a popular practice sounds sensible; it asks what observable evidence can support a bounded decision about an article, ticket, or handoff.`,
  s.methodology,
  s.analysis,
  s.evidenceNotes,
  `The first analytical distinction is between a fact and an interpretation. A ticket may show what the requester reported, when a message arrived, which documented step was attempted, or which owner accepted a transfer. It does not automatically prove cause, authorization, customer understanding, or a completed outcome. For ${s.focus}, the record should preserve the source of each material fact and label the analyst's interpretation separately.`,
  `The cited guidance converges on a narrow operational principle: ${s.finding} In an outsourced helpdesk, that principle keeps tier-one work useful without turning a specialist into the unappointed owner of security, money, policy, identity, or production decisions. The article can explain the supported path, gather permitted evidence, and state the stopping point; an accountable owner decides exceptions and consequential changes.`,
  `A useful comparison separates at least three cohorts. Routine requests can test whether the documented answer is findable and applicable. Boundary cases can test whether the article names a prerequisite, permission condition, or alternate route. Returned or repeated cases can test whether the record left the next owner with enough evidence. Combining those cohorts would conceal the exact condition that makes the guidance safe or unsafe to reuse.`,
  `For daily article creation, the practical unit is not a page view or a keyword. It is a decision that a support record must enable: answer, ask for a permitted fact, pause, redirect, escalate, or confirm an approved result. The article should state the relevant audience, action, evidence threshold, owner, and checkpoint in language a specialist can apply to the request in front of them.`,
  `The sources also caution against treating a control as proof of an outcome. A named owner does not prove that the owner accepted work. A citation does not prove that local policy permits an action. A timestamp does not prove that a customer understood a promise. Those are separate observations and should be measured separately when the helpdesk reviews article use or ticket quality.`,
  `Applied to OutsourcedHelpdeskServices.com, the safest improvement is to connect the article to the existing operating boundary: level-one support can preserve context, follow approved routines, and prepare a clear escalation. It should not invent a missing fact, broaden access, promise an unconfirmed result, or conceal uncertainty in polished prose. The receiving owner should be able to see what is known, what is inferred, and what decision remains.`,
  `A second pass through the evidence should ask what would falsify the working interpretation. For ${s.focus}, a record that appears to support the finding may still be explained by a different cause: a changed product, a new customer population, a missing queue field, an unavailable specialist, or an article that was never visible to the person handling the request. That is why the review should preserve the request wording, route selected, evidence available at the time, and the condition that caused the work to stop. Without those fields, a later reviewer can describe activity but cannot tell whether the article supported the decision.`,
  `The practical comparison is between an applicable answer and a merely similar answer. An applicable answer matches the request type, audience, system state, permitted action, and evidence threshold. A merely similar answer shares vocabulary but changes one of those conditions. In ${s.focus}, that distinction is the main protection against confident reuse. A specialist may use a related article to explain a general concept, but should not silently borrow its authorization, customer promise, escalation destination, or completion criteria. The boundary belongs in the article where the decision is made, not only in training notes.`,
  `A helpdesk record can make this comparison auditable with a compact evidence map: reported goal, observed condition, source or check, interpretation, permitted action, unresolved question, accountable owner, and next customer checkpoint. Each field answers a different question. The reported goal preserves the customer's intent; the observed condition prevents guesses; the source shows how a fact was obtained; the interpretation shows analysis; and the owner identifies who may decide. For ${s.focus}, collapsing these fields into one polished narrative would make an unsupported conclusion look like a verified fact.`,
  `The evidence should also be read over time rather than from one successful example. Compare the first use of the guidance with later uses after a policy, product, access, or ownership change. Look for returned transfers, repeated clarification, corrections to customer updates, requests that were stopped for missing authority, and cases in which personal data was collected but not needed. These are not automatically failures; some are correct boundary behavior. Their value is diagnostic: they show whether the article tells the specialist when to answer, when to ask, and when to stop.`,
  `For an outsourced helpdesk, role separation is part of the result. The frontline specialist can classify the request, search approved guidance, verify permitted facts, minimize the record, explain a supported next step, and preserve the decision request. A client-side service owner, security owner, identity owner, or policy owner may retain the consequential decision. The article should say which role owns each action and what evidence transfers with it. ${s.finding} should therefore be applied as a routing and evidence rule, not as permission for the provider to expand its mandate.`,
  `A useful review question is whether the customer could receive an accurate update while the decision remains open. The update should state what was received, what has been checked, what is waiting, and the event that will trigger the next review. It should not turn a transfer into a resolution or turn an elapsed time into a guarantee. In ${s.focus}, this separates communication quality from decision quality: a clear checkpoint can be successful even when the underlying request still needs another owner, while a reassuring message can be defective if it hides that dependency.`,
  `The same evidence model supports article maintenance. If a reviewer sees the same mismatch in more than one request, record the exact condition rather than rewriting the whole article by instinct. The correction may be a narrower title, a new audience label, an added prerequisite, a separate exception route, a redaction instruction, a backup owner, or a clearer stopping point. Retain the old scope in the change history and test the revised boundary against a routine case and a near-neighbor case. This prevents a local repair from creating a new form of scope drift.`,
  `What the sources do not justify is equally important. Three reputable references can support a principle, but they do not establish a company's local contract, system permissions, staffing pattern, response time, customer outcome, or legal conclusion. The article must not convert institutional guidance into a claim that a particular queue is compliant or that a particular intervention will improve performance. The defensible claim is narrower: the cited principles provide a way to inspect ${s.focus}, while local owners must validate the implementation and decide exceptions.`,
  `The resulting decision rule is deliberately conservative. Keep the request in the documented lane when the audience, action, evidence, and authority all match. Ask for one permitted fact when a missing detail prevents that match. Pause and route when the requested action exceeds the frontline role, the evidence is contradictory, the source scope is unclear, or the accountable owner is unavailable. Record the reason and preserve the customer checkpoint. This rule makes uncertainty visible without abandoning the requester, and it gives the next owner a concrete question instead of an unexplained queue transfer.`,
  `Limitations: the study uses public guidance rather than a representative sample of live helpdesk records. The sources differ in purpose, terminology, publication history, and level of detail. A desk review cannot estimate causal impact, predict individual behavior, establish legal compliance, or show that one article structure improves customer outcomes. Local tools, policies, languages, channels, and owner availability may change the correct implementation.`,
  s.conclusion,
];

const seeds: RepairSeed[] = [scopeDrift, ownerAvailability, queueEvidence, articleConflict, handoffAcceptance, updatePromises, searchIntent, privacyRedaction, exceptionRouting, reviewSampling] as RepairSeed[];

export const aug18ResearchRepair: RepairPost[] = seeds.map((s) => ({ ...s, keyStats: [{ value: '3', label: 'evidence sources' }, { value: '1', label: 'decision boundary' }], body: bodyFor(s), sources: s.sources, related: s.related }));
