type RepairPost = { slug:string; title:string; excerpt:string; minutes:number; published:'2026-08-18'; body:string[] };

const makeBody = (topic:string, decision:string, example:string, boundary:string, review:string) => [
  `This August 18, 2026 help desk guide addresses ${topic} as an operating decision for an outsourced helpdesk. Begin with the requester's goal, the affected service, the evidence already available, and the next safe action. A queue should not treat a familiar phrase as a diagnosis. The specialist records what was observed, what was reported, what remains unknown, and which owner can decide the exception. That discipline makes the article useful across shifts without inventing facts about a particular company, tool, contract, or customer.`,
  `The central decision is ${decision}. Write the trigger, required evidence, permitted action, stopping point, and receiving owner in plain language. A good rule is inspectable: another specialist can follow it and a reviewer can explain why the route was chosen. Keep customer communication separate from internal assumptions. Say what has been received and checked, what is waiting, and when the next checkpoint occurs. Do not promise an outcome controlled by another team.`,
  `A practical scenario is ${example}. Start with the request as it arrives, including the ambiguity that makes triage necessary. Then show the smallest useful clarification, the evidence to record, the permitted response, and the point at which the work moves to an accountable owner. Label facts, assumptions, and open questions separately. This prevents a concise article from encouraging a specialist to guess merely because the queue is busy or the requester describes the issue urgently.`,
  `The outsourced help desk role can acknowledge, classify, search approved guidance, document observable facts, preserve context, and explain an approved next step. It cannot silently approve identity changes, security exceptions, policy interpretations, money decisions, production changes, or unusual access. The boundary here is ${boundary}. When the boundary is reached, retain only the minimum necessary detail, name the decision needed, route it, and give the requester an honest checkpoint.`,
  `Use a ticket note that another owner can continue: customer goal, impact, service or task, source of each material fact, checks completed, unknowns, action already taken, next action, responsible owner, and customer update event. Avoid copying secrets, credentials, recovery codes, or unnecessary personal information. An attachment should be described by what it demonstrates and where it may be reviewed, not duplicated into a broad queue. Good notes reduce repeated questions while preserving uncertainty.`,
  `Knowledge guidance should expose scope before steps. State who the article is for, which request types it covers, prerequisites, examples, exceptions, and the stop condition. Add the words a requester may use, but do not merge cases merely because they share a product name. If an approval, identity check, service owner, or protected record changes the route, put that condition beside the instruction. Findability without a boundary creates confident misrouting.`,
  `Review the workflow with a small, varied sample: routine intake, waiting work, transfers, escalations, recontacts, and closures. Inspect evidence quality, ownership, state accuracy, customer updates, privacy minimization, and whether the specialist stayed within authority. A count is not a conclusion. Separate demand, missing access, unclear articles, unavailable owners, and weak fields before changing a target. The review should identify one source correction rather than turn every variation into individual blame.`,
  `For this topic, ${review}. Record the correction, its effective scope, the owner who approved it, and the cases that remain outside it. Recheck later work against the changed article, field, routing rule, or handoff message. If the evidence does not support a broad change, keep the adjustment narrow. If a decision is blocked, make that dependency visible instead of filling the gap with a plausible answer. A visible stop protects both customer trust and the support role.`,
  `The useful conclusion is not that one queue design fits every help desk. It is that reliable outsourced support makes decisions visible, keeps protected authority with its owner, and gives customers accurate next-step information. Start with one request class, test the wording against real approved examples, and expand only when the evidence shows the boundary is understood. This article is dated August 18, 2026; its date does not imply a company result, credential, testimonial, or universal benchmark.`,
];

const seeds = [
 ['help-desk-customer-goal-intake-card','Build a customer-goal intake card for help desk triage','Capture the outcome behind a vague support request before choosing a queue.','the request is a goal statement, not permission to perform the requested change','a customer asking for access without identifying the task or approved owner','do not infer authorization from a clearly stated goal','compare clarification turns with misroutes and recontacts'],
 ['help-desk-queue-risk-lane-review','Review risk lanes in an outsourced help desk queue','Separate routine work from requests that need an accountable owner.','which queue lane matches the evidence and authority available','a routine setup request that reveals a security-sensitive exception','do not let queue age override the protected route','sample lane changes beside escalations and returned work'],
 ['help-desk-article-scope-marker','Add a scope marker to help desk knowledge articles','Make article applicability visible before a specialist follows a procedure.','whether the reader and request match the article scope','an account guide that applies only after an identity check','do not imply that a scope marker grants permission','review search exits and wrong-article escalations'],
 ['help-desk-ticket-evidence-source-note','Record evidence sources in help desk tickets','Distinguish customer reports, observations, and owner decisions.','what each material fact actually proves','a screenshot that shows a display state but not its cause','do not convert an observation into a technical conclusion','compare source labels with escalation returns'],
 ['help-desk-after-hours-intake-boundary','Set an after-hours intake boundary for help desk work','Define what can be acknowledged outside normal coverage.','which signals require immediate routing and which can wait','a late message describing impact without enough evidence for urgency','do not promise monitoring or restoration outside confirmed coverage','review overnight messages for missed checkpoints'],
 ['help-desk-customer-language-fact-check','Fact-check customer language before help desk replies','Keep replies precise when the record still contains uncertainty.','which statement is verified, pending, or owned elsewhere','a customer asking whether an unconfirmed fix is complete','do not replace uncertainty with reassuring speculation','audit replies against ticket evidence and recontacts'],
 ['help-desk-queue-age-context-review','Put queue age in context for help desk review','Interpret aging alongside ownership, waiting reason, and impact.','whether age signals risk or an expected dependency','an old ticket waiting for a named approval with a current checkpoint','do not close or escalate solely because a timer is high','compare age bands with outcomes and missing owners'],
 ['help-desk-transfer-context-preservation','Preserve context during help desk transfers','Move work without forcing the customer to restate the case.','what the receiving owner must know to accept responsibility','a transfer that includes impact, checks, unknowns, and next customer update','do not treat reassignment as acceptance','review bounced transfers by missing context'],
 ['help-desk-approved-answer-version-check','Check answer versions before help desk replies','Prevent stale guidance from becoming a confident customer answer.','which approved version applies to the current request','an article whose steps are correct only before a documented policy change','do not publish a changed answer without its owner review','compare version use with repeat questions'],
 ['help-desk-identity-checkpoint-handoff','Document an identity checkpoint handoff','Keep account-access work moving without making identity decisions in frontline support.','what has been verified and what the authorized owner must decide','a reset request with an incomplete verification result','do not copy sensitive identity evidence into a broad note','review handoffs for minimum necessary detail'],
 ['help-desk-ticket-duplicate-link-review','Review links between possibly duplicate tickets','Reduce parallel work while preserving distinct customer impact.','whether the owner, scope, timing, and next action truly match','two similar requests with different authorization consequences','do not merge records to make the queue look smaller','sample linked and rejected cases'],
 ['help-desk-waiting-reason-taxonomy','Use a waiting-reason taxonomy in help desk queues','Make paused work explain who or what is awaited.','which dependency permits work to continue','a ticket waiting for customer evidence versus an internal approval','do not use pending to hide missing ownership','compare waiting reasons with age and recontact'],
 ['help-desk-escalation-decision-request','Write the decision request in a help desk escalation','Give a receiving owner a choice they can actually answer.','what decision is requested and which facts support it','an escalation asking whether a documented exception is permitted','do not ask a specialist to guess the owner’s policy decision','review returned escalations for vague asks'],
 ['help-desk-knowledge-search-failure-note','Turn failed knowledge searches into help desk evidence','Use search failure to improve article language and routing.','whether the failure is wording, scope, missing content, or access','a requester term that finds a broad article with the wrong stopping point','do not equate a search hit with a safe answer','group misses by intent and outcome'],
 ['help-desk-customer-update-owner-field','Assign an owner to customer update checkpoints','Keep progress communication owned during technical handoffs.','who must send the next accurate update and what triggers it','a support queue waiting on a technical owner’s acceptance','do not turn an update owner into a resolution approver','compare missed updates with transfer states'],
 ['help-desk-queue-reopen-reason-review','Review why help desk tickets reopen','Use reopening as evidence about answers, ownership, and closure.','what condition shows the original closure was incomplete','a ticket reopened because the answer omitted a prerequisite','do not blame a specialist without checking the source instruction','compare reopen reasons with article and field defects'],
 ['help-desk-sensitive-detail-redaction-note','Minimize sensitive detail in help desk notes','Preserve routing context without widening exposure.','which detail changes the decision and which is unnecessary','a security-related request that needs a category and owner, not a secret','do not paste credentials or private records into ordinary notes','review redaction decisions with the accountable owner'],
 ['help-desk-specialist-stop-condition','Define a stop condition for frontline help desk work','Make escalation a clear safe action rather than a failure.','which observable condition ends the frontline lane','a request that needs a policy exception or protected access','do not continue because the customer is insistent','sample stops for consistency and correct destinations'],
 ['help-desk-service-owner-question-log','Maintain a service-owner question log for help desk gaps','Turn recurring unresolved questions into accountable decisions.','which question needs an owner answer rather than another macro','a repeated request where the public article lacks a scope rule','do not let the log become an unofficial policy record','review age, answer quality, and downstream ticket change'],
 ['help-desk-shift-handoff-open-loop','Close open loops in help desk shift handoffs','Make unfinished work understandable at the next coverage change.','what remains open, why, and when it will be checked','a waiting ticket with a named owner and customer checkpoint','do not mark a handoff complete when the next action is unowned','compare handoff gaps with duplicate follow-ups'],
 ['help-desk-request-channel-fallback','Design a fallback when help desk intake channels fail','Keep requests findable without inventing a second uncontrolled queue.','where a request should go and how it returns to the durable record','a portal interruption with an approved temporary instruction','do not promise that an alternate channel has normal coverage','review recovery for orphaned requests'],
 ['help-desk-quality-sample-rotation','Rotate help desk quality samples by request type','Avoid judging the queue from one easy category.','which sample mix tests the actual operating boundaries','a review covering routine, waiting, transfer, and protected cases','do not infer broad quality from a narrow sample','compare sample coverage with recurring defects'],
];

export const aug18BlogRepair: RepairPost[] = seeds.map(([slug,title,excerpt,topic,decision,example,boundary,review], index) => ({ slug, title, excerpt, minutes: 9 + (index % 2), published: '2026-08-18', body: makeBody(topic, decision, example, boundary, review) }));
