const published='2026-08-31' as const;
type B={slug:string,title:string,excerpt:string,goal:string,evidence:string,decision:string,boundary:string,example:string};
const bs:B[]=[
['first-response-evidence-note','Write a first-response evidence note the next specialist can use','Turn the first reply into a compact record without guessing at causes.','understand the customer outcome before choosing a queue label','the customer wording, affected service, observed symptom, time, and approved checks','routine handling, one bounded clarification, or a named-owner route','Do not diagnose an incident, verify identity through an unapproved channel, or promise a resolution time.','A customer says the portal is not working; the note records their intended task and visible message before asking one route-changing question.'],
['customer-checkpoint-calendar','Build a customer checkpoint calendar for open help desk work','Schedule truthful updates around observable events.','keep every open request connected to a promised communication event','the last action, waiting party, current owner, review time, and next event','an event-driven update, time-driven update, or owner reset of an unsupported promise','A checkpoint is not a completion forecast; never invent another team’s timeline.','A vendor has no estimate, so the desk promises to check Tuesday and report what is known, not to report a fix Tuesday.'],
['ticket-scope-change-record','Record a help desk ticket scope change without losing the original request','Keep new asks and changed impact visible when a conversation grows.','preserve the original outcome while deciding where new work belongs','the original goal, new ask, affected services, risk signal, owner, and promise','one continuing path, a linked ticket, or an owner decision on scope','Do not fold security, billing, access, or production decisions into routine troubleshooting.','A login question becomes an account-owner dispute; the specialist preserves the login work and opens a protected ownership route.'],
['queue-intake-duplicate-signal','Use duplicate signals safely during help desk intake','Recognize related demand while preserving each customer’s impact.','reduce repeated investigation without erasing a distinct request','service, symptom, timing, account context, incident reference, impact, and owner','suggesting a relationship, linking confirmed work, or remaining independent','Similarity is not confirmation; frontline staff must not declare an incident.','Three customers share an error string, but only two share the service and time window, so the third remains separate.'],
['article-fallback-instruction','Add a safe fallback instruction to a help desk article','Give specialists a useful next action when a prerequisite is missing.','prevent stale guidance from becoming improvised permission','the missing prerequisite, article version, observed mismatch, stopped action, and source owner','one permitted question, an approved alternate route, or a source-defect escalation','The fallback must not bypass identity, security, payment, policy, or production controls.','An expected menu has disappeared, so the specialist records the mismatch instead of guessing at a replacement path.'],
['escalation-return-repair','Repair a returned help desk escalation without restarting the ticket','Treat a returned handoff as evidence about the packet, route, or boundary.','restore a decision-ready handoff while preserving completed work','the original question, return reason, missing fact, owner, actions tried, and checkpoint','supplying a permitted fact, changing the route, or naming the correct owner','A return does not transfer protected decision authority to the frontline specialist.','Security returns a request missing the tenant; support can add that identifier but cannot judge whether the event is benign.'],
['shift-start-risk-scan','Run a shift-start risk scan for an outsourced help desk queue','Find unowned, aging, protected, and promise-bearing work first.','begin each shift with accountable work rather than only the newest ticket','unaccepted transfers, impact, protected signals, missed checkpoints, expiring approvals, and absent owners','immediate ownership, a customer update, or duty-owner escalation','The scan prioritizes review; it does not override policy or authorize protected work.','An older ticket awaits the customer while a newer access mismatch has no owner; the unowned protected request is surfaced first.'],
['resolution-evidence-ladder','Create a resolution evidence ladder for help desk tickets','Match closure language to the strongest confirmation available.','state only what the help desk can truthfully claim at closure','the requested outcome, completed action, system evidence, customer evidence, and remaining limit','resolved, completed but unconfirmed, transferred, or still waiting','A sent reply, reassignment, workaround, or silence is not proof of resolution.','A reset link was delivered but access is unconfirmed, so the ticket records delivery and a checkpoint rather than restored access.'],
['knowledge-gap-triage','Triage a help desk knowledge gap before writing an article','Separate missing guidance from missing ownership, access, routing, or authority.','send recurring friction to the smallest repair that can fix it','failed searches, repeat questions, workarounds, returned routes, sources, and owner decisions','an article, synonym, workflow, access fix, owner decision, or no publication','Do not publish a confident answer while the authoritative source is unresolved.','Agents ask how to approve refunds; the gap is authority, so evidence goes to the financial owner rather than a how-to article.'],
['customer-language-preservation','Preserve customer language through help desk routing','Keep the requested outcome visible while adding operational terms.','prevent internal categories from replacing what the customer needs','the original phrase, careful restatement, outcome, observations, and route term','whether the restatement supports routing without an unsupported diagnosis','Never rewrite uncertainty as a confirmed cause or expose protected internal labels.','“My order vanished” becomes “customer cannot locate order 123 in the portal,” not “database sync failure.”'],
['owner-acceptance-proof','Capture proof that a help desk owner accepted the next action','Separate assignment from acceptance with a visible accountable event.','know who agreed to perform or decide the next step','receiving owner, exact question, acceptance event, checkpoint, and return reason','accepted, clarification required, redirected, or duty-owner intervention','A queue assignment, mention, or notification does not prove acceptance.','Engineering is assigned at 10:00, but acceptance occurs at 10:18 when the duty engineer confirms the investigation question.'],
['daily-publishing-source-lock','Use a source lock in the daily help desk publishing routine','Freeze claim, authority, audience, and reviewer for one truthful version.','keep daily publishing tied to an authoritative operating question','source record, access date, supported claim, audience, boundary, reviewer, and trigger','publish, qualify the claim, or stop the article','A source lock cannot make a weak source authoritative or make secrets public.','A product instruction changes during review, so the editor pauses, records the new version, and rechecks the route.']
].map(x=>({slug:`help-desk-${x[0]}`,title:x[1],excerpt:x[2],goal:x[3],evidence:x[4],decision:x[5],boundary:x[6],example:x[7]} as B));
function body(s:B){return[
`Start with one outcome: ${s.goal}. Preserve the requester’s words, add a careful restatement, and label inference so another specialist can separate observation from interpretation.`,
`Build the record from ${s.evidence}. Every field should change the route, permitted action, owner, or customer checkpoint. Exclude unrelated personal data, credentials, and speculation.`,
`The operating choice is ${s.decision}. Write the ordinary path and the condition that changes it. If approved access cannot confirm the condition, preserve the uncertainty and use the named fallback.`,
`${s.boundary} A useful boundary still allows acknowledgement, permitted fact gathering, approved routine work, and a truthful explanation of the next event. Urgency never creates authority.`,
`Worked example: ${s.example} This teaches reasoning, not a promised result. Identify the goal, evidence, action, stop, owner, and next update.`,
`Customer language must match the evidence state: say what arrived, what was checked, what remains unknown, who owns the next decision, and when the queue will check again.`,
`Review a bounded sample of transferred, reopened, and routine tickets. Classify defects as wording, source, route, access, ownership, or boundary problems so the repair reaches the right owner.`,
`For OutsourcedHelpdeskServices.com, this Blog article was published on August 31, 2026. It succeeds when a new specialist can make a safe, explainable next decision while protected decisions remain with authorized owners.`]}
export const aug31BlogArticles=bs.map(s=>({...s,published,minutes:8,body:body(s)}));

const src=[
 {name:'NIST Cybersecurity Framework 2.0',url:'https://www.nist.gov/cyberframework',note:'Governance and risk-management framing.'},
 {name:'ICO data minimisation guidance',url:'https://ico.org.uk/for-organisations/uk-gdpr-guidance-and-resources/data-protection-principles-a-guide-to-the-data-protection-principles/data-minimisation/',note:'Adequate, relevant, and necessary information.'},
 {name:'GOV.UK Service Manual: user needs',url:'https://www.gov.uk/service-manual/user-research/start-by-learning-user-needs',note:'Evidence-led user-needs validation.'},
 {name:'CISA Secure by Design',url:'https://www.cisa.gov/securebydesign',note:'Security ownership and safe-default principles.'}];
type R={slug:string,title:string,excerpt:string,question:string,method:string,finding:string,implication:string,limitation:string,keyStats:{value:string,label:string}[]};
const rs:R[]=[
 {slug:'ticket-context-loss-study',title:'Outsourced help desk ticket context loss: a bounded handoff review',excerpt:'Find where customer goals, evidence, and promises disappear between owners.',question:'Where does decision-relevant context disappear between frontline, specialist, and owner queues?',method:'Select transferred tickets and code goal, facts, action, decision request, acceptance, and promised checkpoint at every handoff.',finding:'The dangerous loss is the unresolved question or customer promise disappearing while a transcript remains attached.',implication:'Use a compact handoff schema and require accept, return with one reason, or redirect to a named destination.',limitation:'This protocol is not a measured company result; privacy limits and local authority maps affect available evidence.',keyStats:[{value:'6',label:'handoff fields'},{value:'3',label:'decision outcomes'}]},
 {slug:'waiting-state-signal-study',title:'Outsourced help desk waiting states: signals for accountable follow-up',excerpt:'Separate customer, owner, vendor, and scheduled-action waits.',question:'Which waiting fields preserve accountability without pretending to control an external outcome?',method:'Compare waiting party, missing condition, watcher, review time, last message, and next event across each waiting reason.',finding:'Generic pending cannot distinguish a healthy dependency from abandoned work; party, watcher, and next event can.',implication:'Design states around the resumption condition and retain a time review when the external event has no deadline.',limitation:'The study does not establish service targets or prove a tool configuration improves outcomes.',keyStats:[{value:'4',label:'waiting classes'},{value:'3',label:'minimum signals'}]},
 {slug:'knowledge-gap-classification-study',title:'Outsourced help desk knowledge gaps: article or operating problem?',excerpt:'Decide when repeated questions justify content and when they require another owner.',question:'How can publishing distinguish a missing article from missing access, ownership, routing, or authority?',method:'Review failed searches, repeated clarifications, returns, workarounds, and source availability; classify the cause.',finding:'Repeated questions prove demand but do not prove that public instructions are the safe remedy.',implication:'Require a stable source, bounded audience, permitted action, reviewer, and retirement trigger before publishing.',limitation:'Classification depends on the sampled queue and cannot establish universal demand or performance.',keyStats:[{value:'6',label:'gap classes'},{value:'5',label:'publication gates'}]},
 {slug:'owner-acceptance-study',title:'Outsourced help desk owner acceptance: assignment is not accountability',excerpt:'Study the event that turns a routed ticket into accepted work.',question:'What evidence shows that the next owner accepted responsibility for an action or decision?',method:'Compare assignment, notification, first response, clarification, redirect, and explicit acceptance in a fixed sample.',finding:'Automated assignment proves routing activity, not human acceptance; accept, clarify, or redirect is testable.',implication:'Track acceptance separately from resolution and give orphaned protected work a duty-owner path.',limitation:'Acceptance varies by system and does not establish resolution time, quality, or staffing sufficiency.',keyStats:[{value:'4',label:'acceptance outcomes'},{value:'2',label:'separate clocks'}]},
 {slug:'resolution-claim-study',title:'Outsourced help desk resolution claims: matching words to evidence',excerpt:'Separate action completed, outcome confirmed, and customer-verified resolution.',question:'Which evidence supports common closure claims without overstating what the queue knows?',method:'Code closed tickets by goal, action, system evidence, owner confirmation, customer confirmation, reopen reason, and wording.',finding:'Internal completion and customer outcome are different states; silence, transfer, and delivery cannot prove resolution.',implication:'Use an evidence ladder and choose wording no stronger than the highest verified rung.',limitation:'Reopen data misses customers who never return and cannot establish a universal closure policy.',keyStats:[{value:'5',label:'evidence rungs'},{value:'4',label:'closure states'}]}
];
function rbody(s:R){return[
`Research question: ${s.question}`,
`Methodology: ${s.method} Freeze the inclusion rule and observation window before reading outcomes. Separate facts from reviewer interpretation and keep restricted artifacts in approved systems.`,
`User-needs frame: GOV.UK guidance recommends learning what users are trying to accomplish and validating needs with evidence. The customer goal therefore remains distinct from a queue label or proposed solution.`,
`Governance frame: NIST CSF 2.0 places governance around risk decisions. This supports naming an accountable owner and boundary; it does not prove a local permission, service level, or result.`,
`Information boundary: ICO data-minimisation guidance supports information that is adequate, relevant, and necessary. Large transcripts and broad screenshots can increase exposure without clarifying a decision.`,
`Primary finding: ${s.finding} Test it with a routine case, near-neighbor, incomplete case, and protected case. Reviewer disagreement signals an unclear condition or owner.`,
`Operational implication: ${s.implication} Frontline specialists may preserve goals, collect permitted facts, follow approved steps, and communicate checkpoints while protected decisions stay with authorized owners.`,
`Security implication: CISA Secure by Design supports security ownership and safe defaults. For help desk work, use explicit stops and accountable routes instead of workarounds.`,
`Limitations: ${s.limitation} Public sources provide principles, not evidence about company customers, staffing, contracts, credentials, or outcomes.`,
`Published August 31, 2026: make the customer goal, evidence, authority boundary, owner event, and truthful checkpoint observable. This date identifies the Research release, not a benchmark.`]}
export const aug31ResearchArticles=rs.map(s=>({...s,slug:`outsourced-helpdesk-${s.slug}`,published,sourceDate:published,body:rbody(s),sources:src,related:[]}));
