export const oct02ResearchSupplements:Record<string,string[]>={
'outsourced-helpdesk-ai-summary-evidence-loss-study':[
`A reconstruction exercise should hide the summary from one reviewer and hide the source timeline from another. Compare the requested outcome, safe next step, facts cited, unknowns retained, owner chosen, and customer checkpoint. Classify disagreements by the missing or altered event rather than reviewer confidence. Repeat after changing conversation length, message order, channel, and the position of a customer correction. This design shows whether loss follows a stable condition such as early-message neglect or whether failures are too irregular for bounded use.`,
`Procurement questions should reach below a vendor accuracy headline. Buyers need to know whether administrators can declare required fields, inspect attribution, prevent automatic action, retain corrections, compare versions, restrict training reuse, and export audit events. They should ask what happens when a model or prompt changes, because validation of one configuration cannot authorize another. Contracts cannot replace testing, but they can assign notification, retention, incident, and remediation duties. Attractive summaries without provenance shift verification work and risk back to the desk.`,
`Quality review should distinguish extraction, compression, and interpretation. An extracted timestamp can be checked against one event. A compressed history requires testing whether omitted turns change meaning. Interpretive statements such as likely cause need a label and may be unsuitable for protected routing. Each class needs different controls. Treating every generated sentence alike encourages blanket trust or blanket rejection. The buyer outcome is a field-level policy linking output class, permitted use, verification, and accountable approval.`,
`Rollout should start with read-only shadow summaries on one request family. Specialists record whether the draft saved time, which source links they opened, what they corrected, and whether they would have chosen a different path without the source. An owner reviews consequential omissions before expansion. If corrections fall, confirm that case mix and detection stayed comparable. Define retirement triggers too: failed trace links, unknown configuration, or degraded protected-field performance should return the desk to source-first handling without losing ownership or checkpoints.`,
`Adversarial review should include negation, corrected names, quoted messages, conflicting timestamps, multiple requesters, and instructions pasted from an untrusted source. The purpose is not to trick a model for sport. These patterns occur in ordinary support and can reverse meaning when compressed. Record whether the summary identifies the speaker and evidence origin, and whether content inside the ticket is treated as data rather than operational instruction. A buyer should expand use only after the system handles these boundary cases through traceable output or a visible uncertainty route.`],
'outsourced-helpdesk-remote-session-consent-study':[
`Consent should be tested as an interaction, not a checkbox. Ask participants to explain which application will be viewed, what the technician may do, whether files may move, how to pause, and what ends control. This is not a policy quiz; it identifies interface language that changes expectations. Run it on desktop and mobile clients, with keyboard-only navigation and assistive technology. When comprehension fails, revise the start sequence or offer another channel rather than treating a recorded click as conclusive evidence.`,
`Privilege needs a separate event model. A tool may connect under the customer's session, request elevation later, or run through an installed service with broader rights. Record which model applies, what prompt appears, who approves, and what actions are logged after elevation. Routine support entitlement must not become standing administration because the software permits it. Sample declined elevation as well as successful actions. Declines are useful control evidence when the change lacks an authorized owner.`,
`File movement is another boundary connection logs can obscure. Define whether clipboard transfer, diagnostic upload, printing, or download is permitted by request type. A technician may need a log fragment but not an entire folder. Record the approved artifact, purpose, destination, retention rule, and deletion owner without copying sensitive contents. Test defaults because automatic clipboard synchronization can move data before either participant notices. Safer configuration reduces reliance on perfect attention during pressured support.`,
`A controlled stop needs a reason, stable device state, evidence already collected, receiving owner, acceptance event, and customer checkpoint. Otherwise staff may work around the boundary to avoid abandoning the person. Review stops for recurring defects: inaccessible consent, unavailable approver, unsupported device, hidden privilege, or residual connection. Repairing those conditions expands safe service capacity more effectively than telling technicians to use better judgment inside an ambiguous session.`],
'outsourced-helpdesk-multilingual-escalation-fidelity-study':[
`Build the glossary from decisions rather than isolated terms. Each protected expression needs an operational rendering, similar phrases that imply a different path, evidence needed to disambiguate, and an owner who approves change. Include negative examples where one verb can mean capability or authorization. Version the glossary and attach its version to reviewed cases. When usage changes, rerun the challenge set rather than quietly replacing a term and assuming historical routes remain comparable.`,
`Channel transitions need observation. A caller may begin in speech, receive an English email recap, and answer through a portal that selects a standardized category. At each transition compare the unresolved question and commitment instead of copying all text. Speech-recognition confidence is not semantic certainty, and a menu choice is not necessarily the speaker's classification. Preserve the original authorized evidence location and link it without widening access.`,
`Customer confirmation should target the fact that changes the route. Asking someone to approve a long translated transcript transfers quality control to the requester and delays urgent work. Confirm whether one service or many are affected, whether a workaround exists, or whether the person requests access versus reports access. Record corrections as new evidence. Do not treat silence as agreement or delay a protected escalation when existing facts already meet its trigger.`,
`Buyers should request evidence about supported language-channel pairs, reviewer availability by shift, protected-term governance, low-confidence escalation, and how complaints change the glossary. Volume alone does not show capability. Five machine-translated languages can provide less dependable decision support than two with qualified boundary review. Each coverage promise needs a named quality mechanism and fallback so commercial pressure does not turn an untested translation into operational authority.`],
'outsourced-helpdesk-saas-offboarding-dependency-study':[
`Source conflicts must be planned. HR may show a departure, the identity provider an active account, and an application owner an approved extension. The coordinator should not choose whichever source is easiest. Name authority by decision: who establishes relationship end, continued access, data custody, and accepted risk. Record the conflict and pause only affected actions while independent safe steps continue. This prevents one ambiguity from freezing the workflow or being ignored for a clean completion metric.`,
`Test rollback and failure before live use. Revocation can interrupt a shared integration, ownership transfer can fail after disablement, and an API can return success before propagation. For reversible steps document restoration authority and evidence. For irreversible steps require approval before execution. A failed action remains owned work with a next attempt or exception; it does not disappear into a closed parent ticket. Synthetic leaver accounts can exercise transitions without exposing real employee data.`,
`Coverage analysis should compare the declared catalogue with authentication, procurement, browser-management, and support evidence available to authorized owners. Tier one should not hunt through every system. The goal is to reveal which discovery source owns each class and where no reliable inventory exists. A newly found application becomes a catalogue finding. Record how it was discovered, which cases may be affected, and who decides retrospective review without rewriting history.`,
`The service boundary should state which applications have executable runbooks, which support only evidence assembly, which require client-only action, and which are out of scope. Each entry needs a backup owner and communication rule. Buyers can then distinguish added coverage from nominal queue availability. The deliverable is a reconciled dependency packet that authorized owners can act on, not a generic assurance that all access everywhere has ended.`],
'outsourced-helpdesk-refund-status-ownership-study':[
`Saved replies need event-specific evidence. Approval wording requires an approval event and named policy owner. Initiation wording requires the commerce system instruction and time. Processor wording should reproduce only an approved non-sensitive state. A receipt claim needs evidence the relevant party can provide. Blank variables should block or narrow a claim rather than invite inference. Review macros whenever terminology, policy, processor integration, or supported geography changes.`,
`A repeat-contact cohort reveals broken checkpoints. Compare customers returning before the review time, after it passed without an update, and after an overstated update. Code what the prior message led them to expect. The remedy may be clearer wording, proactive notification, a shorter internal interval, or a named watcher. It is not automatically more reassurance. Each message should add a verified event or honestly report that none is available while preserving the next owned check.`,
`Refund and security paths must meet without being conflated. An unrecognized charge can require a protected fraud route, but the desk should not declare fraud or solicit authentication data. A policy-disputed refund is not necessarily suspicious. Define observable triggers, minimum evidence, owner, and safe wording for both paths. Test near-neighbours with similar language but different order evidence to show whether workflow follows events or alarming vocabulary.`,
`Buyer diligence should inspect systems and authority together: visible events, timestamp meaning, status documentation, exception approvers, processor contacts, prohibited ticket data, and cross-shift ownership. A continuous inbox adds little if financial decisions wait without backup. A narrow team can still add value through accurate intake, event wording, and checkpoints. Procurement should evaluate that real lane rather than an undefined promise to handle refunds end to end.`]
};
