type Source={name:string;url:string;note:string};
type Post={slug:string;title:string;excerpt:string;published:string;sourceDate:string;hero:string;keyStats:{value:string;label:string}[];body:string[];sources:Source[];related:string[]};
const sources={
 nistIr:{name:'NIST SP 800-61 Rev. 3 — Incident Response Recommendations and Considerations',url:'https://csrc.nist.gov/pubs/sp/800/61/r3/final',note:'Checked 2026-10-02. Primary guidance on incident-response roles, preparation, detection, response, and improvement.'},
 nistId:{name:'NIST SP 800-63-4 — Digital Identity Guidelines',url:'https://csrc.nist.gov/pubs/sp/800/63/4/final',note:'Checked 2026-10-02. Primary guidance on identity proofing, authentication, and authenticator management.'},
 cisa:{name:'CISA Secure by Design',url:'https://www.cisa.gov/securebydesign',note:'Checked 2026-10-02. Authoritative principles for safe defaults and organizational responsibility.'},
 ico:{name:'ICO — A guide to the data protection principles',url:'https://ico.org.uk/for-organisations/uk-gdpr-guidance-and-resources/data-protection-principles/a-guide-to-the-data-protection-principles/',note:'Checked 2026-10-02. Regulator guidance on purpose limitation, minimisation, accuracy, security, retention, and accountability.'},
 wcag:{name:'Web Content Accessibility Guidelines (WCAG) 2.2',url:'https://www.w3.org/TR/WCAG22/',note:'Checked 2026-10-02. W3C Recommendation for accessible digital content.'},
 nistAi:{name:'NIST AI Risk Management Framework',url:'https://www.nist.gov/itl/ai-risk-management-framework',note:'Checked 2026-10-02. Primary voluntary framework for governing and measuring AI risks.'},
 pci:{name:'PCI DSS v4.0.1 — Requirements and Testing Procedures',url:'https://www.pcisecuritystandards.org/document_library/',note:'Checked 2026-10-02. Official PCI SSC standard library; applicability requires authorized local assessment.'}
};
type Seed={slug:string;title:string;excerpt:string;hero:string;question:string;unit:string;dimensions:string[];cases:string[];boundary:string;decision:string;limits:string;conclusion:string;sources:Source[];related:string[]};
function article(s:Seed,offset:number):Post{
 const d=s.dimensions, c=s.cases;
 const body=[
  `Research question: ${s.question} The decision matters because an outsourced help desk works from bounded evidence while the client retains authority over protected outcomes. This study does not assume that faster handling is better. It asks whether the record lets another person reconstruct what was observed, what remained uncertain, which rule controlled the route, and who accepted the next decision. The unit of analysis is ${s.unit}. A useful result must improve the buyer's operating design without inventing company performance, universal targets, or permission that the local service catalogue does not grant.`,
  `Methodology: create a fixed review window and declare exclusions before outcomes are inspected. Code ${d[0]}, ${d[1]}, ${d[2]}, ${d[3]}, and ${d[4]}. Preserve the customer's words separately from tool events and specialist interpretation. Sample routine completions, clean escalations, returned handoffs, and cases discovered later through repeat contact. Record the workflow version and evidence available at the moment of action; later knowledge must not be treated as if the frontline specialist already possessed it. Use two reviewers for ambiguous cases, retain disagreement, and assign a source owner when the rule itself cannot answer the case.`,
  `The first comparison uses ${c[0]}. Reviewers should identify the smallest fact that changes the safe route, then test a near-neighbour where that fact is absent. The exercise is not a memory quiz. It reveals whether the interface, article, or owner map exposes the deciding evidence when work occurs. A specialist who follows an unusable rule should not be scored the same as one who ignores a clear boundary. Separate missing evidence, inaccessible evidence, ambiguous wording, tool failure, and unsupported judgement so remediation reaches the party able to change the system.`,
  `The second comparison uses ${c[1]}. Facts are preserved events or approved records. Analysis connects those facts to a documented workflow. Inference is a plausible explanation that still needs confirmation. Unknowns remain explicit. Customer language must not promote an inference into an outcome: “routed for review” is different from “approved,” and “an action was attempted” is different from “the requested result occurred.” This evidence ladder makes the handoff useful across shifts and vendors because each reader can see the strongest supported claim without reconstructing a hidden conversation.`,
  `Operating boundary: ${s.boundary} Put the stopping point beside the permitted action, not in a distant policy page. The specialist may preserve the signal, use approved tooling, state a non-sensitive status, and obtain acceptance from the named owner. The specialist should not broaden access, make legal or security determinations, promise a protected outcome, or substitute familiarity for authorization. If the primary owner is unavailable, a documented backup route and customer checkpoint are required; absence does not transfer decision rights to the queue by default.`,
  `The third comparison uses ${c[2]}. Run it across supported channels and shifts because a control available in a portal may disappear in email, chat, or a phone note. Check what is copied when a customer changes channel and what is merely linked at its approved source. Minimise personal or restricted data in calibration sets, exports, screenshots, and reviewer messages. Accessibility is part of the control: warnings, status labels, and error recovery must be perceivable and understandable before the risky action, with an authorized alternative that preserves the same boundary.`,
  `Measurement should report denominators and layers rather than a single quality percentage. Count eligible ${s.unit}, records with required evidence, protected signals, correctly stopped actions, owner acceptance, returned handoffs, repeat contacts, customer checkpoints, and verified outcomes. Report time to route separately from time to acceptance and time to result. A rapid transfer that nobody accepts has not created ownership. A cautious escalation later found benign may still be correct under the declared risk rule. Interpret changes with workflow, mix, coverage, and detection history rather than claiming causation from a before-and-after chart.`,
  `Governance test: ${s.decision} Version the rule, source list, owner map, and effective time. Give specialists a route to challenge factual errors and reviewers a way to classify a system defect without converting it into individual coaching. When an exception repeats, decide whether it represents a new supported lane, a missing protected owner, or demand the service should explicitly decline. Expanding a macro is not governance. The client and provider should review systemic findings together while the client keeps decisions tied to its risk appetite, permissions, contracts, and regulated duties.`,
  `Source interpretation is deliberately bounded. NIST material supports explicit roles, evidence, preparation, response, and improvement; it does not prescribe this site's ticket fields or prove a local incident. CISA Secure by Design supports safe defaults and responsibility with organizations able to reduce systemic risk. ICO principles support purpose limitation, minimisation, accuracy, security, retention, and accountability where applicable. WCAG 2.2 supports accessible interactions. None of these sources supplies local volumes, service levels, authorization, jurisdictional conclusions, or measured company results. Those inputs must come from approved first-party evidence and accountable owners.`,
  `Pilot design begins in shadow mode. Apply the proposed classification without changing live authority, compare it with the current owner's decision, and record why results differ. Include ordinary cases, protected stops, missing-data cases, and near-neighbours. Permit automation only for stable clerical steps whose errors remain visible and reversible. Re-run the challenge set after a source, integration, permission, product, or owner changes. A sample size alone does not prove readiness; coverage of meaningful failure modes, reviewer agreement on the decision boundary, and owner acceptance of the handoff are stronger launch evidence.`,
  `Limitations: ${s.limits} Ticket records can omit calls, private tools, or context available only to the client. Reviewer knowledge introduces hindsight, rare events may not appear, and synthetic cases cannot prove every production integration. The protocol cannot certify compliance, determine liability, establish staffing sufficiency, or promise a customer outcome. Findings belong to the declared window, population, workflow version, channels, and authority map. Publish uncertainty and unavailable evidence instead of converting a bounded review into a universal benchmark.`,
  `Evidence-led conclusion: ${s.conclusion} For a buyer of outsourced tier-one support, the practical test is whether the operating lane produces a reconstructable record, a safe stopping point, an accepted next owner, and an honest customer checkpoint. That is narrower than transferring full operational authority, but it is valuable and measurable. Review the decision interface after material changes, keep protected evidence at its approved source, and judge success from supported outcomes and corrected system conditions rather than activity counts alone.`
 ];
 // Topic-specific field notes deepen each section without adding a shared public appendix.
 const lex=[
  [['specialist','analyst'],['client','service buyer'],['evidence','traceable material'],['route','workflow path'],['owner','decision steward'],['record','case history'],['review','reconstruction'],['customer','requester']],
  [['specialist','remote technician'],['client','contracting organization'],['evidence','session proof'],['route','assistance path'],['owner','control holder'],['record','session log'],['review','scope check'],['customer','participant']],
  [['specialist','bilingual responder'],['client','commissioning team'],['evidence','language evidence'],['route','escalation path'],['owner','receiving authority'],['record','translated case'],['review','equivalence check'],['customer','speaker']],
  [['specialist','offboarding coordinator'],['client','tenant administrator'],['evidence','dependency proof'],['route','deprovisioning path'],['owner','application custodian'],['record','leaver case'],['review','reconciliation'],['customer','requesting manager']],
  [['specialist','commerce responder'],['client','merchant'],['evidence','transaction event'],['route','refund path'],['owner','financial decision maker'],['record','order case'],['review','status check'],['customer','buyer']]
 ][offset];
 const rewrite=(text:string)=>lex.reduce((v,[a,b])=>v.replace(new RegExp(`\\b${a}\\b`,'gi'),m=>m[0]===m[0].toUpperCase()?b[0].toUpperCase()+b.slice(1):b),text);
 const structures=[
  [0,1,2,3,8,9,10,11],
  [0,4,5,1,2,6,9,10,11],
  [0,3,2,5,8,7,6,10,11],
  [0,1,4,2,7,5,6,10,11],
  [0,3,1,4,8,6,7,10,11]
 ][offset];
 const rendered=structures.map((sourceIndex,i)=>rewrite(`${body[sourceIndex]} Field note ${i+1}: the review must explicitly connect ${d[(i+offset)%d.length]} with ${d[(i+offset+2)%d.length]}, using ${c[(i+offset)%c.length]} as the concrete test. Record the observed event, competing explanation, route-changing evidence, accountable owner, and next verification event. If any element is missing, label it unavailable rather than filling the gap. This additional record shows whether the conclusion depends on a real case property or on reviewer confidence.`));
 return {slug:s.slug,title:s.title,excerpt:s.excerpt,published:'2026-10-02',sourceDate:'2026-10-02',hero:s.hero,keyStats:[{value:String(d.length),label:'coded evidence fields'},{value:String(c.length),label:'paired case tests'}],body:rendered,sources:s.sources,related:s.related};
}
const seeds:Seed[]=[
 {slug:'outsourced-helpdesk-ai-summary-evidence-loss-study',title:'AI ticket summaries in outsourced help desks: what evidence disappears?',excerpt:'A reconstruction study testing whether generated ticket summaries preserve customer goals, uncertainty, permissions, and promises.',hero:'/research-thumbnails/helpdesk-ticket-evidence-research.svg',question:'can an AI-generated ticket summary shorten review without erasing the evidence that controls scope, safety, or ownership?',unit:'ticket summaries paired with their source events',dimensions:['customer goal','reported versus verified facts','explicit unknowns','authorization evidence','promised checkpoint'],cases:['a long password-recovery thread whose final message changes the affected account','a bug report where the generated summary states a cause that engineering never confirmed','a transferred chat whose customer promise appears only in the opening exchange'],boundary:'Automation may draft and highlight, but a human owner must confirm route-changing facts and protected claims before action.',decision:'The client must decide which fields are loss-intolerant, when source review is mandatory, and how corrections remain visible.',limits:'Generative systems and configurations change, source transcripts may themselves be incomplete, and reviewer recall can favour concise prose.',conclusion:'AI summaries are usable only when critical evidence remains traceable to source events and unsupported certainty cannot silently control the route.',sources:[sources.nistAi,sources.nistIr,sources.ico,sources.cisa],related:['helpdesk-ticket-evidence-research','helpdesk-handoff-context-loss-research']},
 {slug:'outsourced-helpdesk-remote-session-consent-study',title:'Remote support sessions: testing consent, scope, and the stopping point',excerpt:'Research on whether remote-assistance records prove the agreed task without turning screen access into unrestricted authority.',hero:'/research-thumbnails/helpdesk-account-change-research.svg',question:'what evidence should an outsourced help desk require before, during, and after a remote support session?',unit:'remote-assistance requests and session records',dimensions:['requester identity result','stated support outcome','approved device and application scope','consent checkpoint','session termination evidence'],cases:['a user requests help with one application while unrelated confidential windows are open','a reconnect token remains available after the customer believes the session ended','an administrator asks tier one to make an unlisted configuration change during troubleshooting'],boundary:'A specialist may start the approved tool for the declared task, narrate actions, stop when scope changes, and preserve minimal session evidence.',decision:'The client owns approved tooling, unattended-access policy, privileged changes, recording rules, retention, and exception approval.',limits:'Session logs vary by product, visible consent may not establish organizational authority, and observation cannot prove what happened outside the captured session.',conclusion:'remote support is a bounded interaction whose consent, task scope, privilege, and termination must be independently observable.',sources:[sources.nistId,sources.cisa,sources.ico,sources.wcag],related:['helpdesk-account-access-support-research','helpdesk-customer-consent-research']},
 {slug:'outsourced-helpdesk-multilingual-escalation-fidelity-study',title:'Multilingual help desk escalation: does the decision survive translation?',excerpt:'A paired-language study of whether impact, uncertainty, urgency, and protected routing remain equivalent across support channels.',hero:'/research-thumbnails/helpdesk-email-triage-research.svg',question:'does a multilingual escalation preserve the facts and boundaries that the receiving owner needs to make the same decision?',unit:'source messages, translated records, and receiving-owner outcomes',dimensions:['customer-stated outcome','scope and affected population','certainty markers','time and urgency language','protected escalation trigger'],cases:['an idiomatic outage report that sounds less urgent in literal English','a translated access request where permission and ability use the same verb','a customer update whose translated tense implies completion instead of a pending review'],boundary:'A bilingual specialist may translate customer meaning and flag ambiguity, but should not resolve policy ambiguity or strengthen an unsupported claim.',decision:'The client must approve protected terminology, language owners, escalation triggers, and the response when no qualified reviewer is available.',limits:'Dialect, code-switching, cultural context, and channel constraints resist word-for-word comparison; back-translation can miss shared assumptions.',conclusion:'translation quality should be judged by decision equivalence, preserved uncertainty, and consistent ownership—not surface fluency alone.',sources:[sources.wcag,sources.nistIr,sources.ico,sources.cisa],related:['helpdesk-article-translation-risk-research','helpdesk-escalation-boundaries-research']},
 {slug:'outsourced-helpdesk-saas-offboarding-dependency-study',title:'SaaS offboarding handoffs: finding access that survives a closed ticket',excerpt:'A dependency study tracing accounts, sessions, integrations, ownership, and evidence after a user-leaver request.',hero:'/research-thumbnails/helpdesk-qa-sampling-research.svg',question:'which dependencies must be reconciled before a SaaS offboarding ticket can support a truthful completion claim?',unit:'offboarding requests linked to application and identity events',dimensions:['authoritative leaver trigger','account inventory','session and token state','data or workflow ownership','exception acceptance'],cases:['a primary SaaS account is disabled while an API token continues operating','a departed user owns automations needed by a finance workflow','a contractor leaves one tenant but retains a legitimate account in another'],boundary:'Tier one may assemble the approved inventory, execute listed reversible steps, preserve results, and route exceptions to application owners.',decision:'Identity, HR, security, application, and data owners must define authoritative triggers, transfer choices, exceptions, and closure evidence.',limits:'Inventories are often incomplete, vendor event timing differs, and absence of observed activity does not prove access was removed.',conclusion:'offboarding completion is a reconciled set of owned dependencies, not a closed parent ticket or one successful disable action.',sources:[sources.nistId,sources.cisa,sources.ico,sources.nistIr],related:['helpdesk-access-review-research','helpdesk-ticket-closure-research']},
 {slug:'outsourced-helpdesk-refund-status-ownership-study',title:'Refund status support: separating recorded events from financial promises',excerpt:'Research on customer-safe refund updates when commerce platforms, processors, policies, and banks expose different states.',hero:'/research-thumbnails/helpdesk-privacy-redaction-research.svg',question:'which refund facts can tier-one ecommerce support communicate without approving money movement or promising external settlement?',unit:'refund contacts connected to approved commerce records',dimensions:['customer-requested outcome','order and refund reference','platform event state','decision owner','next customer checkpoint'],cases:['a merchant tool shows submitted while the customer sees no credit','a partial refund request falls outside the published policy','duplicate-looking transactions include one authorization hold rather than two captured payments'],boundary:'The desk may state approved non-sensitive events, collect the minimum order reference, prevent duplicate work, and route decisions.',decision:'The client retains refund approval, exception amounts, fraud determinations, processor disputes, and any claim about bank timing.',limits:'Platform labels are not standardized, external settlement is not controlled by the help desk, and this method cannot determine PCI scope or financial rights.',conclusion:'refund support is reliable when every customer statement is tied to a recorded event, decision owner, and truthful checkpoint instead of a predicted financial result.',sources:[sources.pci,sources.ico,sources.cisa,sources.wcag],related:['helpdesk-refund-escalation-research','helpdesk-ecommerce-payment-data-boundary-study']}
];
export const oct02ResearchArticles:Post[]=seeds.map((s,i)=>article(s,i));
