export const researchSearchRouteStudy = { slug:'outsourced-helpdesk-search-route-study', title:'Outsourced helpdesk search intent: separating similar words from the same route', excerpt:'How customer language, system conditions, and authority boundaries should be compared before guidance is reused.', published:'2026-08-20', sourceDate:'2026-08-20', hero:'/research-heroes/outsourced-helpdesk-search-route-study.png', keyStats:[{value:'4',label:'intent dimensions'},{value:'2',label:'paired cases'}], body:[
'Research question: when two outsourced-helpdesk requests use similar language, what evidence shows that they share an answer path, and what evidence shows that they need different guidance or owners? Search intent is an operational routing question here, not a pageview exercise. A wrong match can send a routine specialist toward an unauthorized action or hide a protected exception behind familiar wording.',
'Evidence scope and method: compare paired requests by stated goal, affected service, system or account condition, requested action, evidence available, and authority required. Include a routine case and a near-neighbor case that changes one material condition. Record the result found, route selected, customer explanation, and final owner. This identifies boundary failures; it cannot estimate search quality across every channel or population.',
'GOV.UK user-needs guidance supports starting with the requester’s problem instead of a presumed content solution. Atlassian’s service-level guidance illustrates why a measure needs a defined event and denominator. Together they support a disciplined review: identify the problem, define what counts as a useful route, and avoid turning a keyword match into a performance claim. The local helpdesk still supplies the case evidence.',
'Similar words can conceal different permissions. “Access” may mean reading a public instruction, checking a permitted account state, or granting a privileged role. “Outage” may mean one user’s symptom or a confirmed incident. “Urgent” may describe impact, emotion, or a contractual priority. The article should expose the condition that changes the lane instead of allowing the search term to decide silently.',
'The record should preserve customer language without treating it as diagnosis. The requester reports an experience. The specialist records an observed condition and the source used to verify it. Analysis connects those facts to a candidate route. An owner decides a protected exception. This sequence matters because fluent copy can make an inference look like a fact while the customer is waiting for an answer.',
'Use four outcomes: same article and action; same concept but a different prerequisite; clarification before routing; and a different owner. Measure them separately. “Found an article” is not success if the page was outside the audience or caused a wrong handoff. A clear stop can be correct when the request requires identity, security, money, policy, or production authority.',
'For daily article work, search findings should lead to the smallest safe correction. Add an example when the boundary is known but hard to recognize. Add a prerequisite when one fact changes the path. Create a separate page when audiences or decisions diverge. Improve routing when no article can legitimately answer the request. Retire a misleading synonym when it repeatedly creates the wrong match.',
'Review the cost of a wrong match, not only the frequency of a successful click. A routine misroute may create another transfer; an account or security misroute may expose information or create an unauthorized expectation. Record impact and authority separately so consequential errors remain visible beside harmless matches. Prioritize a warning, example, or stop condition based on decision risk rather than traffic alone.',
'The title and summary should make the supported lane recognizable without promising to cover every neighbor. State audience, outcome, prerequisite, and excluded decision close to the search result. The first screen should confirm fit. If the request does not fit, the page should offer a safe alternate route or a reason to stop. This is more useful than forcing the reader to infer scope after work has begun.',
'Evaluate discovery and application as separate events. Finding the page is only the first step; the specialist must still confirm conditions and authority. Recording both events prevents search improvement from being mistaken for decision improvement. It also identifies whether the smallest repair is language, indexing, a prerequisite, a route, or an ownership map. The conclusion should match the event the evidence actually covers.',
'Search review should be conducted at the point where the specialist chooses a route, not only in an analytics dashboard. Preserve the query or customer phrase, the result presented, the condition checked, and the action selected. Then compare a successful match with a near-neighbor that changed one material fact. If the same result appears for both, the title, synonym, or article boundary may be too broad. If the result is different but the first screen does not explain why, the search surface still creates avoidable uncertainty. This evidence distinguishes findability work from authority work and protects customers from a polished page that answers a nearby question while the actual request waits for an owner.',
'A route review should also record the safe customer checkpoint. The specialist can explain that the request was received, identify the next owner, and avoid claiming that a search result settled a protected question. That preserves trust while evidence is still being checked. It also gives later reviewers a visible distinction between discovery and resolution.',
'Limitations: search logs and ticket language are incomplete; channel vocabulary changes; and a correct route can still leave the underlying request open. Public sources cannot establish local priorities, permissions, or outcomes. This study cannot prove that a title change improves service. It provides a bounded comparison method for an outsourced helpdesk’s search and routing decisions.',
'Evidence-led conclusion: search intent should be tested against goal, condition, requested action, and authority, with near-neighbor cases used to expose unsafe reuse. Similar words can start discovery but cannot establish applicability. A safe stop or escalation is a valid outcome when the evidence does not support a shared path.'
], sources:[{name:'GOV.UK user needs',url:'https://www.gov.uk/service-manual/user-research/start-by-learning-user-needs',note:'Supports problem-first framing.'},{name:'Atlassian service-level agreements guide',url:'https://www.atlassian.com/itsm/service-request-management/slas',note:'Supports defined measures.'},{name:'NIST Cybersecurity Framework 2.0',url:'https://www.nist.gov/cyberframework',note:'Supports risk-aware routing.'}], related:['helpdesk-article-demand-evidence-gap-research','helpdesk-article-audience-fit-research'] };
