export const researchScopeFitStudy = { slug:'outsourced-helpdesk-scope-fit-study', title:'Outsourced helpdesk article scope: testing whether guidance fits the requester', excerpt:'Research on audience, prerequisites, permissions, and stop conditions before a support article is reused.', published:'2026-08-20', sourceDate:'2026-08-20', hero:'/research-heroes/outsourced-helpdesk-scope-fit-study.png', keyStats:[{value:'5',label:'scope tests'},{value:'2',label:'boundary cohorts'}], body:[
'Research question: which observable fields show that a helpdesk article fits the requester and the requested action, rather than merely sharing vocabulary with the ticket? In outsourced support, an instruction can be technically accurate yet operationally unsafe when the audience, account state, permission, or decision owner differs from the case. This study treats scope as an evidence question that can be tested before reuse.',
'Methodology and evidence scope: review a fixed sample of routine requests and near-neighbor cases across access, account, billing, product-use, and security-related language. Record reader role, customer goal, affected service, prerequisites, allowed action, source authority, stop condition, and final owner. Compare cases that matched the article with cases that looked similar but needed clarification or escalation. This is a qualitative boundary study, not a universal reuse rate.',
'A scope statement should answer who may use the page, under which conditions, and what may happen after the facts are confirmed. “How to add a user” can describe a self-service explanation, an access request, or a privileged-role approval. “Payment problem” can describe a public status explanation or a refund decision. The shared noun does not establish a shared support path. The material condition belongs near the first action.',
'The near-neighbor test is the center of the method. Hold the wording constant while changing one condition: the requester’s authority, the system state, the sensitivity of the request, or the owner required. If the permitted action changes, the article must expose that fork. If the evidence is missing, the specialist should ask only the approved question or stop and route. Similarity is useful for discovery, not permission.',
'GOV.UK user-needs guidance supports starting with the user’s problem, while NIST CSF 2.0 and GAO control guidance support accountable information and control activities. These sources support inspectable boundaries; they do not grant an outsourced specialist authority in a customer environment. Local policy, contract, identity process, and product state still determine what the provider may explain or do.',
'For this niche, a frontline specialist can find approved guidance, verify permitted facts, explain a supported step, and prepare a clear handoff. The specialist should not infer consent, broaden access, disclose secrets, decide a policy exception, or turn an unknown into a confident answer. A good article makes the stopping point as visible as the happy path, so a careful pause is recognized as correct work.',
'Measure fit with paired outcomes: same article and same action; same concept but a missing prerequisite; clarification before routing; and a different owner. A high reuse count can hide overreach, while a high stop count can be correct when the sample contains protected work. The useful finding is not “reuse more,” but “make the intended boundary testable and reduce unexamined scope jumps.”',
'Reviewers should separate observation from interpretation. An observation might be that the requester’s role was recorded, a product state was visible, or an owner accepted a transfer. The interpretation is that the article applies. A citation explains the principle behind a check; it does not prove that local policy permits the action. Keeping these layers distinct helps later writers correct the right claim instead of rewriting a whole page.',
'The repair should be proportional. Narrow the title when the page attracts the wrong audience. Add a prerequisite when one missing fact changes the path. Add a stop condition beside a sensitive step. Split the page when two audiences require different permissions or owners. Improve routing when no article can legitimately decide the request. Preserve the original decision context so a future edit does not erase why the boundary existed.',
'A repeatable review gives two reviewers the same routine and near-neighbor cases without revealing the expected result. Each names the applicable article, missing fact, allowed action, owner, and customer checkpoint. Disagreement is evidence about the content or policy boundary, not automatically evidence of individual failure. Resolve the ambiguity at the smallest authoritative source and test the pair again after the change.',
'The scope record should be usable at the moment a specialist opens the page. Put the supported audience and first prerequisite near the title, then name the excluded decision before the detailed explanation. A reader under queue pressure should not have to finish the article to learn that the request belongs to an owner. Reviewers can test this by showing only the search result and opening section to two people, then asking them to state the permitted action and stopping point. If their answers differ, the problem is visible before a customer is affected. Keep examples tied to the conditions actually studied, and label a hypothetical neighbor as analysis rather than a local fact. This makes concise guidance safer to maintain and gives the helpdesk a concrete reason to split a page serving incompatible audiences.',
'Limitations: roles, permissions, products, and contracts change; public sources cannot resolve local rules; and ticket notes may omit why a specialist believed an article applied. The study cannot prove that one design improves customer outcomes or that every near-neighbor has been sampled. Its claim is bounded to observable fit tests for an outsourced helpdesk.',
'Evidence-led conclusion: reuse is supportable when audience, prerequisite, authority, and stopping point can be checked against the request. If those fields cannot be established, matching words are insufficient. The correct result is clarification or escalation, not a broader article. This keeps daily knowledge work useful while protecting customers from confident guidance outside the provider’s role.'
], sources:[{name:'GOV.UK user needs',url:'https://www.gov.uk/service-manual/user-research/start-by-learning-user-needs',note:'Supports user-goal framing.'},{name:'NIST Cybersecurity Framework 2.0',url:'https://www.nist.gov/cyberframework',note:'Supports risk and governance boundaries.'},{name:'GAO Standards for Internal Control',url:'https://www.gao.gov/products/gao-14-704g',note:'Supports accountable control activities.'}], related:['helpdesk-article-audience-fit-research','helpdesk-knowledge-article-creation-research'] };
