const published = '2026-09-02' as const;

type BlogSeed = {
  slug: string; title: string; excerpt: string; outcome: string; inputs: string;
  route: string; stop: string; example: string;
};

const blogSeeds: BlogSeed[] = [
  {slug:'help-desk-first-response-evidence-note',title:'Write a first-response evidence note that survives a handoff',excerpt:'Capture the request, verified facts, uncertainty, and next owner before the first reply leaves the queue.',outcome:'create a durable first-pass record that another specialist can use without replaying the conversation',inputs:'customer goal, reported symptom, verified context, unknowns, permitted checks, current owner, and next checkpoint',route:'send an approved answer, request one route-changing fact, or prepare a named handoff',stop:'Do not present a reported symptom as a diagnosis or copy unnecessary sensitive material into the note.',example:'A user reports that payroll is unavailable; the note records one affected account and an untested wider scope, then routes the access check to its owner.'},
  {slug:'help-desk-vendor-wait-review',title:'Review help desk tickets waiting on a vendor',excerpt:'Keep external dependencies visible with an owner, evidence state, follow-up event, and honest customer checkpoint.',outcome:'distinguish a controlled vendor wait from work that has quietly lost accountability',inputs:'vendor case reference, requested decision, last vendor event, customer impact, internal owner, follow-up time, and fallback route',route:'continue the bounded wait, ask the internal owner for a decision, or escalate a missed dependency checkpoint',stop:'A vendor case number does not transfer responsibility for the customer promise.',example:'The vendor has acknowledged a defect but offered no date; the help desk records the next vendor check and gives the customer that checkpoint without inventing restoration timing.'},
  {slug:'help-desk-closure-evidence-check',title:'Check closure evidence before resolving a help desk ticket',excerpt:'Separate an attempted action from a verified outcome and document why the queue can safely stop work.',outcome:'close only when the documented completion condition or approved closure policy is satisfied',inputs:'requested outcome, action taken, observed result, customer confirmation when required, unresolved risk, owner, and closure rule',route:'resolve with evidence, retain a bounded confirmation wait, or return the ticket to active ownership',stop:'Do not treat a sent link, executed command, or silent customer as proof of success unless the approved rule says so.',example:'A reset link was delivered but access was not tested; the ticket remains in a confirmation state rather than being labeled restored.'},
  {slug:'help-desk-queue-label-change-control',title:'Control a help desk queue-label change without breaking reports',excerpt:'Map meaning, routing, automations, dashboards, and ownership before renaming or replacing a working label.',outcome:'change a queue label while preserving its operational meaning and downstream evidence',inputs:'current definition, proposed definition, entry and exit rules, automations, reports, saved views, owner, and effective date',route:'approve the mapped change, stage a monitored migration, or return it for dependency review',stop:'A cosmetic rename is not harmless when automation or reporting interprets the old value.',example:'A team replaces “pending” with two waiting reasons only after updating the dashboard and defining who watches each state.'},
  {slug:'help-desk-escalation-return-triage',title:'Triage an escalation returned to the help desk',excerpt:'Turn a rejected or incomplete handoff into a specific repair instead of bouncing the ticket between teams.',outcome:'identify why the receiving owner returned the work and restore one accountable next action',inputs:'requested decision, return reason, missing evidence, scope boundary, customer promise, current owner, and review time',route:'repair the handoff, redirect it to the correct owner, or continue approved frontline work',stop:'Do not resend an unchanged escalation or ask the customer for information already present.',example:'Engineering returns a ticket because no reproduction time is shown; the specialist adds the logged timestamp and resubmits to the same named owner.'},
  {slug:'help-desk-article-source-expiry-review',title:'Review a help desk article when its source expires',excerpt:'Pause unsupported claims, preserve safe guidance, and assign the evidence decision instead of deleting blindly.',outcome:'keep article reuse aligned with a current authoritative source',inputs:'expired source, affected claims, operational risk, replacement evidence, linked macros, article owner, and review deadline',route:'replace the citation, narrow or pause affected instructions, or retire the article through its dependency path',stop:'An inaccessible source does not automatically prove the claim false, but it cannot continue as the only verifiable support.',example:'A vendor removes an old configuration page; the editor pauses the version-specific step while retaining a separately sourced contact route.'},
  {slug:'help-desk-customer-update-after-transfer',title:'Send a truthful customer update after a queue transfer',excerpt:'Explain what moved, what remains open, who owns the next action, and when the customer will hear again.',outcome:'preserve customer expectations when responsibility moves between support lanes',inputs:'customer goal, confirmed work, reason for transfer, receiving owner, acceptance event, unresolved question, and next checkpoint',route:'confirm accepted ownership, report a pending handoff honestly, or reset an unsupported promise',stop:'Do not tell the customer that another team is working until acceptance or another approved ownership event exists.',example:'A billing request is routed to the account team; support says the handoff is awaiting acceptance and commits only to checking it at 15:00.'},
  {slug:'help-desk-known-error-article-check',title:'Check a known-error article before using it on a new ticket',excerpt:'Confirm scope, version, symptoms, workaround limits, and current ownership before reusing a familiar answer.',outcome:'apply known-error guidance only when the new request fits its supported conditions',inputs:'service and version, observed symptom, affected scope, prerequisite evidence, workaround effect, expiry trigger, and owner',route:'use the approved workaround, gather one permitted differentiator, or route to investigation',stop:'Similarity in error wording is not enough to declare the same cause or promise the same outcome.',example:'Two users see “unable to sync,” but only one is on the affected client version; the other ticket follows the diagnostic route.'},
  {slug:'help-desk-unowned-ticket-sweep',title:'Run an unowned-ticket sweep without mass reassignment',excerpt:'Find work with no accepted next owner and route each item by evidence, risk, and the actual decision needed.',outcome:'restore accountable action to orphaned tickets without hiding the underlying workflow defect',inputs:'queue state, last owner event, customer impact, next action, required skill or authority, promise due time, and fallback owner',route:'obtain owner acceptance, use the documented duty route, or escalate a missing ownership rule',stop:'Bulk assignment changes a field but does not prove that people accepted or can perform the work.',example:'Five tickets show an empty assignee; three enter routine triage, one goes to the access owner, and one exposes a missing billing fallback.'},
  {slug:'help-desk-sensitive-attachment-stop',title:'Use a safe stop when a help desk attachment contains sensitive data',excerpt:'Limit exposure, preserve the necessary signal, and route handling to the owner defined by policy.',outcome:'respond to an over-shared attachment without spreading its contents through the support workflow',inputs:'approved data classification, minimum incident reference, affected system, exposure path, authorized owner, containment instruction, and customer-safe wording',route:'follow the protected handling procedure, restrict access, or request owner direction through the approved channel',stop:'Do not download, duplicate, quote, or redistribute the attachment merely to make the escalation feel complete.',example:'A screenshot includes recovery codes; the specialist stops routine troubleshooting and references the protected record without copying the codes into notes.'},
  {slug:'help-desk-reopen-reason-coding',title:'Code a reopened help desk ticket by the reason work resumed',excerpt:'Distinguish failed outcomes, incomplete confirmation, new scope, and unclear closure so the repair reaches the right owner.',outcome:'turn a reopen event into an actionable workflow or content finding',inputs:'original goal, closure basis, new customer evidence, current scope, prior owner, reason category, and next checkpoint',route:'resume the original work, open and link a distinct request, correct guidance, or review the closure rule',stop:'A reopen count alone cannot show whether the specialist, article, product, or customer expectation caused the return.',example:'A ticket reopens because a temporary workaround expired; it is coded as an incomplete outcome rather than a new request.'},
  {slug:'help-desk-daily-article-demand-check',title:'Run a daily demand check before drafting a help desk article',excerpt:'Use ticket evidence, failed searches, repeat questions, risk, and ownership to choose the next useful article.',outcome:'select article work from an observable support need rather than publishing volume alone',inputs:'repeat ticket pattern, customer language, failed searches, current answer, risk boundary, source owner, and likely reuse lane',route:'draft a new bounded answer, improve an existing article, change routing, or record that no article is needed',stop:'Do not create duplicate guidance when the real defect is search wording, ownership, access, or a broken form.',example:'Six searches for “change account owner” lead to a permissions article; the team adds a scoped discovery path instead of duplicating the approval instructions.'}
];

function blogBody(seed: BlogSeed) {
  return [
    `Define the operating outcome first: ${seed.outcome}. Preserve the customer request and separate reported facts, verified evidence, and unresolved interpretation.`,
    `Collect only ${seed.inputs}. Each field should change a permitted action, route, owner, or checkpoint; leave credentials and unrelated personal data outside the ordinary ticket.`,
    `Choose among ${seed.route}. Record the observable condition that selected the path and identify the evidence another specialist can inspect.`,
    `${seed.stop} The safe lane still includes acknowledgement, bounded fact gathering, approved routine steps, and a truthful update event.`,
    `Worked example: ${seed.example} The record should retain the goal, evidence state, next action, stop condition, owner, and customer checkpoint.`,
    `After use, review a small mix of routine, transferred, reopened, and protected tickets. Classify defects as wording, source, route, access, ownership, or boundary issues and send each repair to its accountable owner.`,
    `For OutsourcedHelpdeskServices.com, this Blog article was published on September 2, 2026. Success means daily article creation produces guidance that a new specialist can use safely without inheriting authority that belongs elsewhere.`
  ];
}

export const sep02BlogArticles = blogSeeds.map(seed => ({...seed, published, minutes: 8, body: blogBody(seed)}));

const sources = [
  {name:'NIST Cybersecurity Framework 2.0',url:'https://www.nist.gov/cyberframework',note:'Governance and accountable risk decisions.'},
  {name:'ICO data minimisation guidance',url:'https://ico.org.uk/for-organisations/uk-gdpr-guidance-and-resources/data-protection-principles-a-guide-to-the-data-protection-principles/data-minimisation/',note:'Adequate, relevant, and necessary information.'},
  {name:'GOV.UK Service Manual: measuring user needs',url:'https://www.gov.uk/service-manual/measuring-success/measuring-user-needs',note:'Evidence-based service measures and user outcomes.'},
  {name:'CISA Secure by Design',url:'https://www.cisa.gov/securebydesign',note:'Security ownership and safe-default principles.'}
];

type ResearchSeed = {slug:string;title:string;excerpt:string;question:string;method:string;finding:string;implication:string;limitation:string;keyStats:{value:string;label:string}[]};
const researchSeeds: ResearchSeed[] = [
  {slug:'helpdesk-first-response-evidence-study',title:'Help desk first-response evidence: a handoff-readiness study',excerpt:'Examine which first-pass fields let another specialist continue without replaying the customer exchange.',question:'Which evidence elements make an initial ticket response usable after ownership changes?',method:'Code a fixed sample for customer goal, reported fact, verified fact, unknown, permitted action, stop condition, owner, and checkpoint.',finding:'A quick acknowledgement preserves contact but does not by itself create a transferable operating record.',implication:'Pair the first reply with a compact evidence note and measure whether the next owner can identify the permitted action without rereading the thread.',limitation:'The protocol does not establish response speed, customer satisfaction, or an ideal field count for every queue.',keyStats:[{value:'8',label:'coded elements'},{value:'1',label:'handoff test'}]},
  {slug:'helpdesk-vendor-dependency-accountability-study',title:'Help desk vendor dependencies: an accountability checkpoint study',excerpt:'Compare external case activity with internal ownership and customer promises.',question:'What evidence distinguishes a controlled vendor dependency from a ticket that has lost accountability?',method:'Review a fixed sample for vendor reference, requested outcome, last external event, internal owner, follow-up event, customer promise, and fallback route.',finding:'External acknowledgement shows that a dependency exists but not that the help desk customer commitment has an active internal owner.',implication:'Retain an internal watcher and explicit review event until a verified outcome or approved closure condition occurs.',limitation:'Vendor tools expose different events, and this bounded method cannot evaluate vendor quality or contractual compliance.',keyStats:[{value:'7',label:'dependency fields'},{value:'2',label:'ownership layers'}]},
  {slug:'helpdesk-closure-evidence-sufficiency-study',title:'Help desk closure evidence: a sufficiency-boundary study',excerpt:'Study when attempted actions are mistaken for completed customer outcomes.',question:'Which closure records support the requested outcome, and which show only that support attempted a step?',method:'Compare the customer goal with action evidence, observed result, required confirmation, unresolved risk, closure rule, and later reopen evidence.',finding:'The most important boundary is between proof of an action and proof that the customer outcome occurred.',implication:'Define closure conditions by request type and preserve an explicit unconfirmed state when the evidence supports only an attempted action.',limitation:'Later silence does not reveal the customer outcome, and reopen behavior cannot measure every inaccurate closure.',keyStats:[{value:'6',label:'closure checks'},{value:'2',label:'evidence states'}]},
  {slug:'helpdesk-queue-taxonomy-change-study',title:'Help desk queue taxonomy changes: a dependency-impact study',excerpt:'Trace how label definitions affect routing, automation, reporting, and customer checkpoints.',question:'Which operational dependencies must be reviewed when a queue state or category changes meaning?',method:'Map selected labels to definitions, entry rules, exit rules, automations, reports, saved views, articles, and accountable owners.',finding:'A label change can preserve visible wording while silently changing routing or historical measurement.',implication:'Version the definition, map downstream consumers, set an effective date, and sample both routing and reporting after migration.',limitation:'Undocumented exports and informal team interpretations may remain outside the dependency map.',keyStats:[{value:'8',label:'dependency classes'},{value:'1',label:'effective date'}]},
  {slug:'helpdesk-daily-article-demand-evidence-study',title:'Daily help desk article demand: an evidence-selection study',excerpt:'Evaluate whether ticket patterns and failed searches justify a new article, an edit, or a workflow repair.',question:'What evidence supports creating a new help desk article rather than changing an existing answer, search route, form, or owner map?',method:'Code candidate topics by repeated user goal, customer vocabulary, current result, source authority, risk boundary, maintenance owner, and alternative repair.',finding:'Repeated questions indicate demand, but they do not establish that a new page is the correct intervention.',implication:'Use a daily selection gate that compares new publication with revision, synonym, routing, form, and ownership repairs.',limitation:'Observed demand varies by window and channel; the protocol cannot predict traffic or prove that publication improves resolution.',keyStats:[{value:'7',label:'selection fields'},{value:'5',label:'repair options'}]}
];

function researchBody(seed: ResearchSeed) {
  return [
    `Research question: ${seed.question}`,
    `Methodology: ${seed.method} Freeze the inclusion rule and observation window before reviewing outcomes, and keep restricted artifacts in approved systems.`,
    'User-needs frame: GOV.UK guidance supports defining success around what users need to accomplish and choosing evidence that reflects that outcome. A queue event is therefore not automatically a customer outcome.',
    'Governance frame: NIST CSF 2.0 supports explicit risk governance and accountable decisions. It does not establish a local permission, service level, or operational result.',
    'Information boundary: ICO data-minimisation guidance supports using information that is adequate, relevant, and necessary. Additional transcripts or attachments are not automatically stronger evidence.',
    `Primary finding: ${seed.finding} Test the interpretation against a routine case, near-neighbor, incomplete case, and protected case.`,
    `Operational implication: ${seed.implication} Frontline specialists can preserve goals, gather permitted facts, follow approved steps, and communicate checkpoints while protected decisions remain with authorized owners.`,
    'Security implication: CISA Secure by Design supports security ownership and safe defaults. Explicit stops and accountable routes are preferable to improvised workarounds.',
    `Limitations: ${seed.limitation} Public sources supply principles, not evidence about OutsourcedHelpdeskServices.com customers, contracts, credentials, staffing, or outcomes.`,
    'Published September 2, 2026: this Research release provides a bounded review protocol, not a performance benchmark or universal causal claim.'
  ];
}

export const sep02ResearchArticles = researchSeeds.map(seed => ({...seed, published, sourceDate: published, hero:'/helpdesk-team.jpg', body:researchBody(seed), sources, related:[]}));
