const published = '2026-09-09' as const;
const heroImage = '/helpdesk-team.jpg' as const;

const blogSeeds = [
  { slug: 'help-desk-first-reply-fact-check', title: 'Fact-check the first help desk reply before it leaves the queue', excerpt: 'Use a short pre-send check to keep the first answer accurate, bounded, and useful.', body: ['A fast first reply still needs a factual foundation. Before sending, compare the customer goal, affected service, observed symptom, and current ticket state with the words in the draft.', 'Check names, dates, links, and any statement that an action is complete. Replace a guessed cause with the observed behavior, and distinguish an acknowledgement from an investigation result.', 'Give the customer one usable next step and a named checkpoint. If identity, payment, security, policy, or production access is involved, stop at the documented boundary and route the decision.', 'Review corrections to first replies each week. Repeated errors usually point to a stale macro, unclear source article, or missing queue field—not a need for agents to write more cautiously in the abstract.'] },
  { slug: 'help-desk-shift-start-macro-check', title: 'Check saved help desk replies at the start of a shift', excerpt: 'Catch stale links, hours, names, and promises before a saved reply reaches a customer.', body: ['Saved replies reduce typing, but they also preserve yesterday’s assumptions. Start each shift by checking the small set of macros most likely to be used that day.', 'Open the destination links, confirm coverage hours and contact names, and read the message in the customer view. Verify that each promised action still has a real owner.', 'Do not quietly improvise around a broken approved reply. Mark it unavailable, use a verified alternative when one exists, and send the repair to the content owner.', 'Log the macro, defect, temporary handling, owner, and review time. The routine should be brief and risk-led rather than a daily reread of the entire library.'] },
  { slug: 'help-desk-unassigned-ticket-rescue', title: 'Rescue an unassigned help desk ticket without creating two owners', excerpt: 'Make one person accountable for the next safe action while preserving the queue record.', body: ['An unassigned ticket is a service risk even when several people can see it. The rescue begins when one permitted owner accepts the next action in the shared record.', 'Confirm the customer goal, current impact, last public update, due checkpoint, and any protected decision. Record acceptance before drafting a reply so another specialist does not start parallel work.', 'Ownership of the next action is not authority to approve an exception. Route access, financial, security, contractual, and production decisions to the accountable owner with the evidence attached.', 'Review how tickets became unassigned: automation, absence, rejected routing, or incomplete intake. Repair the route that produced the gap instead of relying on repeated manual rescues.'] },
  { slug: 'help-desk-vendor-status-page-check', title: 'Read a vendor status page before citing it in a support reply', excerpt: 'Match the posted service, region, time, and incident state to the customer’s reported problem.', body: ['A vendor status banner can provide context, but it does not automatically explain an individual ticket. Check the affected product, region, start time, update time, and current incident wording.', 'Record what the page actually confirms and keep the customer report separate. A simultaneous symptom may be related, unrelated, or still too early to classify.', 'Link the official page when it helps, but do not promise vendor recovery or close the ticket solely because the banner turns green. Follow the local verification and ownership rule.', 'After recovery, compare the ticket timeline with the published incident window. Repeated mismatches are a reason to improve the diagnostic route, not to stretch the status notice into evidence it never supplied.'] },
  { slug: 'help-desk-attachment-name-review', title: 'Rename help desk attachments so the next owner can find the evidence', excerpt: 'Use descriptive, low-risk filenames without exposing customer or account details.', body: ['Files called image1 or document-final force the next owner to open every attachment. A useful name identifies the evidence type and event without placing sensitive data in a broadly visible label.', 'Use a stable pattern such as service, symptom, and capture date. Keep customer names, email addresses, account numbers, secrets, and unsupported diagnoses out of filenames.', 'Preserve the original evidence according to policy and note any approved redaction or conversion. Renaming must not imply that an attachment was verified when it was only received.', 'Sample attachments that were hard to locate during handoffs. Adjust the naming guide when agents repeatedly need information that the permitted filename cannot safely carry.'] },
  { slug: 'help-desk-customer-correction-response', title: 'Respond well when a customer corrects the help desk record', excerpt: 'Acknowledge the correction, preserve the earlier wording, and show what changes next.', body: ['A customer correction is new evidence, not an invitation to rewrite history. Keep the original message and add the corrected fact with its source and time.', 'State plainly what you now understand, which routing or troubleshooting step changes, and who owns it. Correct any public summary that would otherwise mislead the next reader.', 'Do not frame the update as customer fault or claim the correction proves a cause. If the new fact changes identity, security, payment, or approval handling, return to the protected process.', 'Review corrections for recurring intake ambiguity. A clearer question or selectable option may prevent the same misunderstanding without making the form longer for everyone.'] },
  { slug: 'help-desk-ticket-merge-safety-check', title: 'Run a safety check before merging two help desk tickets', excerpt: 'Confirm identity, scope, ownership, and promises before combining related requests.', body: ['Similar subjects do not prove that two tickets represent the same need. Compare the requester, affected service, timing, symptom, impact, permissions, and requested outcome.', 'Choose the surviving record, preserve both histories, transfer open actions and customer checkpoints, and make the communication owner visible before changing status.', 'Do not merge records when doing so would cross customer, tenant, privacy, legal, security, or access boundaries. Use a permitted relationship marker when context must remain separate.', 'Audit merged tickets for lost replies, missing attachments, and reopened work. If the same false match recurs, change the detection rule or confirmation step.'] },
  { slug: 'help-desk-priority-downgrade-note', title: 'Explain a help desk priority downgrade in the ticket', excerpt: 'Tie the change to current evidence, remaining impact, ownership, and the next review point.', body: ['Lowering priority should describe a changed condition, not simply a quieter customer or an aging request. Record the earlier signal and the new evidence that changes the handling path.', 'Note what remains affected, any workaround, the next owner, and the customer checkpoint. Keep service restoration separate from final resolution when follow-up work is still open.', 'A frontline specialist should not override incident, security, contractual, or regulated priority rules. Send disputed classifications to the named authority without erasing the original decision.', 'Compare downgraded tickets with later re-escalations. Patterns can reveal weak definitions, premature recovery assumptions, or missing monitoring evidence.'] },
  { slug: 'help-desk-language-preference-handoff', title: 'Carry a customer language preference through a help desk handoff', excerpt: 'Preserve the requested language and translation limits without guessing fluency or meaning.', body: ['A language preference should travel with the active customer need. Record the customer’s stated preference and the channel where it applies, using the approved field rather than an informal label.', 'Keep technical identifiers and quoted error text exact. When translation is used, distinguish customer wording, translated wording, and support interpretation so the next owner can see what changed.', 'Do not infer nationality, location, literacy, or consent from a language choice. Route sensitive or high-impact translation needs through the approved service and review path.', 'Review handoffs for repeated re-asking and meaning loss. Improve the visible field, glossary, or escalation trigger when the same terms create uncertainty.'] },
  { slug: 'help-desk-callback-window-confirmation', title: 'Confirm a help desk callback window without overpromising', excerpt: 'Name the date, time zone, contact route, purpose, and owner of the next call.', body: ['A callback window is useful only when both sides can interpret it. Write the calendar date, start and end time, time zone, contact method, and purpose.', 'Confirm the number or approved channel without copying unnecessary personal details into public notes. Record who will call and what happens if the customer cannot be reached.', 'A window is not a guarantee of resolution. Describe it as a contact commitment unless the accountable owner has approved a specific outcome.', 'Check missed callbacks for conversion mistakes, unavailable owners, and unclear contact consent. Fix the scheduling path rather than widening every window by default.'] },
  { slug: 'help-desk-closure-evidence-check', title: 'Check closure evidence before resolving a help desk ticket', excerpt: 'Match the closure reason to a verified outcome, customer expectation, and any remaining work.', body: ['A completed task, a temporary workaround, and a request for which the customer stopped replying are different endings. Select the closure state that the record can support.', 'Check the original goal, action taken, observable result, customer message, open dependencies, and ownership of follow-up. Keep a policy closure distinct from confirmed success.', 'Do not treat silence as consent, erase unresolved risk, or close protected work because its decision owner is slow. Use the documented waiting and escalation paths.', 'Review reopens and corrections by closure reason. The useful question is which evidence was missing or misunderstood, not which agent closed the most tickets.'] },
  { slug: 'help-desk-daily-broken-link-log', title: 'Keep a daily broken-link log for help desk guidance', excerpt: 'Turn a failed support link into a contained workaround, named repair, and verified replacement.', body: ['When a help desk link fails, record the source article or macro, visible label, intended audience, failure observed, and time checked. Test from the permitted customer view.', 'Name the content owner and any dependent replies or forms. If an authoritative replacement exists, verify its destination and scope before using it.', 'Do not bypass access controls, cite an unverified mirror, or leave a guessed URL in customer guidance. Remove the link from active use when no safe replacement is available.', 'Close the log item only after the published source and its important dependencies are checked. Recurring failures may justify monitoring the source rather than expanding the daily manual check.'] },
] as const;

export const sep09BlogArticles = blogSeeds.map((article) => ({ ...article, published, minutes: 8, heroImage }));

const sources = [
  { name: 'NIST Cybersecurity Framework 2.0', url: 'https://www.nist.gov/cyberframework', note: 'Governance, accountability, risk, and measurement.' },
  { name: 'NIST SP 800-53 Rev. 5', url: 'https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final', note: 'Audit records, access control, and information handling.' },
  { name: 'ICO data minimisation guidance', url: 'https://ico.org.uk/for-organisations/uk-gdpr-guidance-and-resources/data-protection-principles-a-guide-to-the-data-protection-principles/data-minimisation/', note: 'Personal data should be adequate, relevant, and limited to what is necessary.' },
  { name: 'GOV.UK Service Manual: measuring user needs', url: 'https://www.gov.uk/service-manual/measuring-success/measuring-user-needs', note: 'Measures should connect to user outcomes.' },
  { name: 'CISA Secure by Design', url: 'https://www.cisa.gov/securebydesign', note: 'Security ownership and safe defaults.' },
] as const;

const researchSeeds = [
  { slug: 'helpdesk-first-reply-correction-study', title: 'First help desk replies: a correction-pattern study', excerpt: 'A bounded review of which claims are corrected after the first public answer.', question: 'Which fields in first replies most often require a later factual correction?', method: 'Freeze a dated sample of first public replies and their ticket histories. Two authorized reviewers code customer goal, service, stated cause, action status, link, promised event, correction type, and correction time. Report agreement and unresolved cases.', finding: 'The design separates factual corrections from ordinary progress updates and tests whether correction types cluster around a source, macro, or intake field.', use: 'Repair the controlling source when a correction pattern repeats; do not score speed as accuracy.', limitation: 'Later ticket text may omit verbal corrections, reviewers may disagree about materiality, and an observed association cannot show that a macro caused the error.', stats: [{ value: '8', label: 'coded fields' }, { value: '2', label: 'reviewers' }] },
  { slug: 'helpdesk-unassigned-ticket-exposure-study', title: 'Unassigned help desk tickets: an exposure-window study', excerpt: 'Measure time without accepted ownership while separating visibility from accountable action.', question: 'How long do eligible tickets remain without a recorded owner who accepted the next safe action?', method: 'Predefine channels, dates, eligible states, the ownership-acceptance event, and pause rules. For each ticket, record arrival, routing attempts, visible assignees, acceptance, customer checkpoint, protected decision, and final path.', finding: 'The method tests whether dashboard visibility understates intervals in which nobody has accepted a next action.', use: 'Change routing, backup, or acceptance controls where exposure concentrates, while keeping approval authority with its named owner.', limitation: 'System assignment may not reflect human awareness, offline coordination may be missing, and the study does not prove that unassigned time caused a poor outcome.', stats: [{ value: '7', label: 'timing fields' }, { value: '1', label: 'acceptance event' }] },
  { slug: 'helpdesk-ticket-merge-reversal-study', title: 'Merged help desk tickets: a reversal and loss review', excerpt: 'Test whether merging preserves customer promises, evidence, and boundaries.', question: 'Which observable conditions appear in ticket merges that are later reversed or followed by missing-context corrections?', method: 'Take a fixed cohort of merges and a declared follow-up window. Code matching evidence, tenant and requester boundaries, surviving record, transferred promises, attachments, owner, reversal, and missing-context event. Review restricted cases only with authorized staff.', finding: 'The study evaluates merge integrity without assuming that similar text proves a shared customer need.', use: 'Add confirmation fields or narrower match rules where reversals and context loss share a documented condition.', limitation: 'Rare harmful merges may not appear in a small sample, reversals are an incomplete proxy for error, and local tooling limits generalization.', stats: [{ value: '9', label: 'merge fields' }, { value: '2', label: 'follow-up outcomes' }] },
  { slug: 'helpdesk-callback-window-reliability-study', title: 'Help desk callback windows: a reliability protocol', excerpt: 'Compare stated contact windows with attempted contact while keeping resolution separate.', question: 'How often does an eligible callback occur within its stated date, time zone, and window?', method: 'Freeze an observation period and eligibility rule. Code the promised window, zone, owner, approved channel, attempt timestamp, reach result, reschedule, and resolution status. Calculate the within-window share with its numerator, denominator, and exclusions.', finding: 'The protocol measures contact reliability; it does not use a successful callback as evidence that the underlying request was resolved.', use: 'Correct scheduling, ownership, or time-zone handling when misses concentrate in a repeatable step.', limitation: 'System timestamps may differ from customer receipt, abandoned calls may be hard to classify, and the result cannot isolate the cause of a missed window.', stats: [{ value: '8', label: 'callback fields' }, { value: '1', label: 'declared denominator' }] },
  { slug: 'helpdesk-broken-guidance-link-study', title: 'Broken help desk guidance links: a dependency study', excerpt: 'Map failures from source articles into macros, forms, and customer replies.', question: 'When an approved guidance link fails, which customer-facing dependencies still point to it and how long do verified repairs take?', method: 'Define a fixed inventory and observation window. Check links from a permitted external view, then code HTTP result, destination mismatch, source owner, dependent surfaces, containment time, verified replacement, and closure time. Do not follow restricted links without authorization.', finding: 'The study distinguishes a network response from a usable, audience-appropriate destination and maps the repair beyond the first page found.', use: 'Prioritize links by customer use and risk, then close repairs only after material dependencies pass a second check.', limitation: 'Point-in-time checks can miss intermittent failures, access controls can resemble broken links, usage data may be incomplete, and the design does not estimate customer harm.', stats: [{ value: '8', label: 'dependency fields' }, { value: '2', label: 'verification checks' }] },
] as const;

export const sep09ResearchArticles = researchSeeds.map((study) => ({
  slug: study.slug, title: study.title, excerpt: study.excerpt, published, sourceDate: published, hero: heroImage,
  keyStats: study.stats.map((stat) => ({ ...stat })), sources: [...sources], related: [],
  body: [
    `Research question: ${study.question}`,
    `Methodology and scope: ${study.method} This is a proposed operational study for OutsourcedHelpdeskServices.com, not a report of observed customer results.`,
    'Evidence basis: NIST CSF 2.0 and NIST SP 800-53 support accountable, reviewable controls. ICO guidance supports necessary and proportionate personal-data handling. GOV.UK guidance connects measures to user outcomes. CISA supports secure defaults and named security ownership. These reputable sources inform the protocol; they supply no local queue results.',
    `Finding to test: ${study.finding}`,
    `Operational use: ${study.use} Keep observations, reviewer judgments, and inferences in separate fields.`,
    `Inference limits and limitations: ${study.limitation} Results would apply only to the declared sample, period, definitions, and available records; they cannot establish causality, universal benchmarks, customer satisfaction, or legal compliance.`,
    'Published September 9, 2026. Report sample size, exclusions, missing data, denominators, reviewer disagreement, and protocol changes with every result.',
  ],
}));
