const published = '2026-09-07' as const;

type BlogSeed={slug:string;title:string;excerpt:string;goal:string;steps:string;boundary:string;example:string};
const blogSeeds:BlogSeed[]=[
  {slug:'help-desk-first-response-evidence-check',title:'Check the evidence before a help desk first response',excerpt:'Separate the customer report, verified facts, open questions, and next owned action before replying.',goal:'make the first response useful without overstating what support knows',steps:'read the full request, identify the customer goal, verify available account and service facts, record unknowns, and set an owned checkpoint',boundary:'Do not present a customer report as a confirmed cause or promise a resolution time without an approved basis',example:'A user reports that billing caused a lockout; the reply confirms receipt and the identity-safe recovery route without guessing at the cause'},
  {slug:'help-desk-unassigned-ticket-sweep',title:'Run an unassigned-ticket sweep without hiding queue risk',excerpt:'Find ownerless work, assign the next safe action, and keep protected decisions with authorized owners.',goal:'turn unassigned tickets into explicit ownership decisions',steps:'filter new and reopened work, check routing evidence, name the next permitted action, assign an owner, and record the next review time',boundary:'Do not assign sensitive approval work to a general queue merely to clear the unassigned count',example:'A routine setup question moves to tier one, while an ownership dispute is routed to the account owner with its evidence intact'},
  {slug:'help-desk-customer-checkpoint-calendar',title:'Build a customer-checkpoint calendar from ticket promises',excerpt:'Convert time-bound customer commitments into reviewable events without creating a second case record.',goal:'keep promised updates visible across shifts and dependencies',steps:'capture the ticket link, promised event, due time, owner, dependency, and completion evidence in an approved view',boundary:'The calendar is a reminder surface; the ticket remains the authoritative record',example:'A vendor reply expected Tuesday creates a Tuesday checkpoint, not a claim that the vendor will resolve the issue'},
  {slug:'help-desk-missing-information-request',title:'Ask for missing help desk information in one focused message',excerpt:'Request only the facts needed for the next safe action and explain why they matter.',goal:'reduce avoidable back-and-forth while limiting unnecessary data collection',steps:'identify the blocked decision, list the minimum required fields, provide a safe submission route, and state what happens next',boundary:'Never request passwords, recovery codes, or unrelated personal data',example:'For a browser defect, support asks for version, steps, expected result, and a redacted screenshot rather than an unrestricted screen recording'},
  {slug:'help-desk-priority-change-review',title:'Review a help desk priority change before applying it',excerpt:'Tie urgency changes to approved impact evidence, ownership, and a customer checkpoint.',goal:'keep priority meaningful when new evidence arrives',steps:'compare the current impact and urgency rule, document the new evidence, identify the authorized owner, and update the response checkpoint',boundary:'Customer frustration or ticket age alone does not automatically authorize a priority change',example:'A single-user inconvenience remains routine, while verified payroll access failure follows the approved high-impact route'},
  {slug:'help-desk-saved-reply-safety-review',title:'Review a saved help desk reply before reusing it',excerpt:'Check intent, facts, permissions, dates, links, and promises before sending templated language.',goal:'gain drafting speed without sending an answer that does not fit',steps:'match the request goal, replace placeholders, verify product state and links, remove unsupported certainty, and confirm the next action',boundary:'A saved reply cannot override an identity, privacy, payment, or security rule',example:'A cancellation template is adapted to the customer plan and current policy instead of promising an unavailable refund'},
  {slug:'help-desk-vendor-waiting-state',title:'Manage the vendor-waiting state in a help desk queue',excerpt:'Keep ownership and customer communication active while an external provider investigates.',goal:'prevent external dependencies from becoming silent internal delays',steps:'record the vendor case, requested action, last evidence, internal owner, customer checkpoint, and escalation trigger',boundary:'Do not imply that a vendor accepted or resolved work unless its recorded event proves it',example:'Support notes the vendor case number and promises its own next update while the internal owner retains accountability'},
  {slug:'help-desk-resolution-confirmation-step',title:'Add a confirmation step before closing help desk work',excerpt:'Compare the customer goal with observable completion evidence before marking a ticket resolved.',goal:'close on a supported outcome rather than an internal action alone',steps:'restate the goal, verify the completion event, test required access where permitted, communicate any limits, and record the closure basis',boundary:'A handoff, reply, or status change is not automatically a resolved customer outcome',example:'Reset instructions were sent, but the ticket closes only after the approved completion condition is met'},
  {slug:'help-desk-shift-end-promise-check',title:'Run a shift-end check for open customer promises',excerpt:'Review due updates, blocked actions, owner changes, and acceptance evidence before leaving coverage.',goal:'carry unfinished commitments into the next shift without ambiguity',steps:'sort checkpoints due before the next overlap, update customers from verified facts, request acceptance, and flag unaccepted high-risk work',boundary:'Do not transfer authority that the receiving specialist does not have',example:'The next shift accepts a log-collection action while the security decision stays with the named incident owner'},
  {slug:'help-desk-article-source-change-watch',title:'Watch authoritative sources for help desk article changes',excerpt:'Connect high-use guidance to a named source, review trigger, owner, and safe withdrawal path.',goal:'find stale instructions before routine reuse spreads them',steps:'record the controlling source, affected claim, change signal, review owner, dependent macros, and temporary stop condition',boundary:'A changed source requires review; it does not prove every linked instruction is wrong',example:'A vendor updates its recovery flow, so the article owner pauses the affected step and checks linked replies'},
  {slug:'help-desk-escalation-return-path',title:'Define the return path for a help desk escalation',excerpt:'State what decision or evidence lets escalated work return to frontline ownership.',goal:'prevent specialist queues from becoming indefinite holding areas',steps:'name the requested decision, accepting owner, expected evidence, customer checkpoint, return owner, and completion condition',boundary:'Frontline support should not interpret silence as approval',example:'Security returns a documented access decision, after which tier one can communicate the approved next step'},
  {slug:'help-desk-daily-article-candidate-review',title:'Review a daily help desk article candidate before drafting',excerpt:'Test whether the support need calls for new content or a smaller search, routing, form, or ownership repair.',goal:'make daily publishing respond to evidence instead of a quota',steps:'compare repeated customer goals, existing answers, failed searches, workflow friction, source authority, maintenance ownership, and a follow-up measure',boundary:'Do not create a duplicate article when navigation or an existing answer is the actual failure',example:'Missed searches for an existing reset guide lead to synonym improvements and measurement rather than another reset page'}
];

function blogBody(s:BlogSeed){return [`The operating goal is to ${s.goal}. Begin with the customer outcome and the evidence needed for the next observable event.`,`Daily routine: ${s.steps}. Keep the ticket as the durable source of truth and make the owner and review time visible.`,`Separate what the customer reported from what support verified. Record open questions plainly so another shift can continue without treating an assumption as fact.`,`Boundary: ${s.boundary}. When that boundary is reached, preserve permitted evidence, explain the next route, and send the decision to the authorized owner.`,`Example: ${s.example}. The customer-facing message should match the internal evidence state.`,`Review a small weekly sample for missed promises, bounced ownership, excess data, stale language, and repeated questions. Assign each repair to one owner with a follow-up date.`,`Published September 7, 2026 for OutsourcedHelpdeskServices.com. A useful daily article improves a real support routine and has a clear maintenance owner.`]}
export const sep07BlogArticles=blogSeeds.map(s=>({...s,published,minutes:8,heroImage:'/helpdesk-team.jpg',body:blogBody(s)}));

const sources=[
  {name:'NIST Cybersecurity Framework 2.0',url:'https://www.nist.gov/cyberframework',note:'Governance, roles, risk, and reviewable outcomes.'},
  {name:'NIST SP 800-53 Rev. 5',url:'https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final',note:'Accountability, audit, access, and information-protection controls.'},
  {name:'ICO data minimisation guidance',url:'https://ico.org.uk/for-organisations/uk-gdpr-guidance-and-resources/data-protection-principles-a-guide-to-the-data-protection-principles/data-minimisation/',note:'Personal data should be adequate, relevant, and limited to what is necessary.'},
  {name:'GOV.UK Service Manual: measuring user needs',url:'https://www.gov.uk/service-manual/measuring-success/measuring-user-needs',note:'Service measures tied to whether users achieve their goals.'},
  {name:'CISA Secure by Design',url:'https://www.cisa.gov/securebydesign',note:'Clear security ownership and safe defaults.'}
];
type ResearchSeed={slug:string;title:string;excerpt:string;question:string;method:string;finding:string;implication:string;limitation:string;keyStats:{value:string;label:string}[]};
const researchSeeds:ResearchSeed[]=[
  {slug:'helpdesk-first-response-claim-quality-study',title:'Help desk first responses: a claim-quality study protocol',excerpt:'A bounded method for testing whether first replies distinguish reports, verified facts, unknowns, and next actions.',question:'Which response elements help reviewers distinguish acknowledged customer claims from verified service facts?',method:'Freeze a ticket sample and code the customer goal, reported symptom, verified fact, open question, allowed action, owner, and checkpoint before reviewing outcomes.',finding:'A quick response can acknowledge and route work without asserting an unsupported cause or resolution time.',implication:'Score factual separation and next-action ownership separately from response speed.',limitation:'The protocol does not establish customer satisfaction, causality, or a universal response-time target.',keyStats:[{value:'7',label:'coded fields'},{value:'2',label:'separate claim states'}]},
  {slug:'helpdesk-unassigned-work-ownership-study',title:'Unassigned help desk work: an ownership-control study',excerpt:'Examine when assignment events create actionable ownership and when they merely move a queue item.',question:'What evidence shows that previously unassigned work has gained a capable owner and a reviewable next action?',method:'Sample unassigned tickets across request types and code routing basis, authority, acceptance event, first action, exception, and customer checkpoint.',finding:'Queue assignment records location; effective ownership also requires authority, acceptance, and a defined next action.',implication:'Measure time to accepted action separately from time to assignment.',limitation:'Tool events may imply acceptance differently, and the study cannot infer competence or customer harm from timestamps alone.',keyStats:[{value:'6',label:'ownership signals'},{value:'2',label:'timing measures'}]},
  {slug:'helpdesk-resolution-evidence-study',title:'Help desk resolution evidence: a closure-basis study',excerpt:'A repeatable protocol for comparing internal completion events with the customer outcome recorded at closure.',question:'Which closure evidence demonstrates that the supported customer goal was completed or responsibly bounded?',method:'Define closure categories, double-code a fixed sample, and compare the stated goal, action taken, observable result, customer communication, remaining limit, and reopen event.',finding:'An internal action such as sending instructions or transferring work does not by itself prove the customer outcome.',implication:'Record a closure basis and review ambiguous cases separately from confirmed, bounded, and customer-abandoned outcomes.',limitation:'Silence is ambiguous, later reopens miss silent failures, and observational records cannot prove that closure wording caused an outcome.',keyStats:[{value:'6',label:'closure fields'},{value:'4',label:'outcome classes'}]},
  {slug:'helpdesk-saved-reply-fit-study',title:'Saved help desk replies: a reuse-fit research protocol',excerpt:'Study whether templated language matches intent, product state, permissions, evidence, and the next safe route.',question:'Which checks identify when a saved reply is safe to adapt versus when a different workflow is required?',method:'Code request intent, applicable product state, prerequisites, permissions, factual claims, links, promises, and escalation boundary for a fixed sample.',finding:'Text similarity can identify a candidate reply but cannot establish that its claims and actions fit the request.',implication:'Review fit failures by field and repair the source reply, routing rule, or workflow that produced them.',limitation:'The method cannot prove resolution quality, and local policy determines which permissions and promises are allowed.',keyStats:[{value:'8',label:'fit checks'},{value:'1',label:'safe next route'}]},
  {slug:'helpdesk-content-candidate-selection-study',title:'Daily help desk content: a candidate-selection study',excerpt:'Compare article creation with edits, search tuning, form changes, routing fixes, and ownership repairs.',question:'When recurring support demand appears, what evidence supports choosing a new article over a smaller operational repair?',method:'Predefine the user goal, existing coverage, failed-search language, workflow gap, source stability, risk, maintenance owner, alternatives, and follow-up measure.',finding:'Repeated demand justifies investigation but does not establish that another public page is the smallest maintainable intervention.',implication:'Select the intervention before drafting and measure the intended operational event after release.',limitation:'Demand varies by channel and season; without a comparison design, later change cannot be attributed solely to the intervention.',keyStats:[{value:'6',label:'intervention types'},{value:'1',label:'follow-up measure'}]}
];
function researchBody(s:ResearchSeed){return [`Research question: ${s.question}`,`Method: ${s.method} Freeze definitions, exclusions, and the observation window before reading outcomes; keep protected evidence in approved systems.`,`Evidence frame: GOV.UK guidance supports measuring user outcomes. NIST CSF 2.0 and SP 800-53 support governance, accountability, and reviewable controls, but do not define a local service level or prove a help desk result.`,`Information frame: ICO data-minimisation guidance supports limiting personal information to what is necessary. CISA Secure by Design supports clear security ownership and safe defaults; neither source authorizes a local identity or access decision.`,`Finding to test: ${s.finding} Include routine, exception, incomplete, and transferred cases and report counts with their denominators.`,`Operational implication: ${s.implication} Keep observed events separate from inferred causes and record disagreements.`,`Scope and limitations: ${s.limitation} Public sources provide principles, not evidence about OutsourcedHelpdeskServices.com customers, staffing, contracts, tools, or performance.`,`Published September 7, 2026. This Research article defines a falsifiable review protocol; it is not a benchmark, customer study, legal opinion, or universal causal claim.`]}
export const sep07ResearchArticles=researchSeeds.map(s=>({...s,published,sourceDate:published,hero:'/helpdesk-team.jpg',body:researchBody(s),sources,related:[]}));
