const published = '2026-09-04' as const;

type BlogSeed = {slug:string;title:string;excerpt:string;goal:string;routine:string;boundary:string;example:string};

const blogSeeds: BlogSeed[] = [
  {slug:'help-desk-morning-queue-control-routine',title:'A morning queue-control routine for outsourced help desks',excerpt:'Open the day by finding aging promises, missing owners, blocked work, and customer updates that need attention.',goal:'turn the first queue review into a short list of owned actions',routine:'sort by missed customer checkpoint, unassigned work, protected request, and oldest active ticket; then name the next action and review time',boundary:'Do not change priority merely because a ticket is old; impact and the approved priority rule still govern.',example:'An overnight password request has an owner and a current update, while a newer payroll-access ticket has neither. The second ticket receives the first ownership action.'},
  {slug:'help-desk-ticket-promise-register',title:'Keep a ticket promise register without building another queue',excerpt:'Track only customer commitments that need a future action, owner, and observable completion event.',goal:'make time-bound customer promises visible without duplicating every ticket field',routine:'record the promise, due time, accountable owner, dependency, last evidence, and completion condition in a queue view or report',boundary:'A reminder is not a second source of truth; the underlying ticket remains the operating record.',example:'Support promised an update after a vendor check at 14:00. The register points to that ticket and closes only when the update event is recorded.'},
  {slug:'help-desk-escalation-acceptance-checkpoint',title:'Add an acceptance checkpoint to help desk escalations',excerpt:'Confirm that the receiving owner has accepted the requested decision before support releases its follow-up duty.',goal:'prevent escalated tickets from becoming ownerless between queues',routine:'state the requested decision, evidence location, urgency basis, customer checkpoint, receiving owner, and acceptance event',boundary:'Moving a ticket or mentioning a team does not prove accepted ownership.',example:'A suspected account takeover moves to security. Support keeps the customer checkpoint until a named security owner accepts the investigation.'},
  {slug:'help-desk-knowledge-answer-preflight',title:'Run a preflight before sending a help desk knowledge answer',excerpt:'Check audience, product state, prerequisites, risk, and the next safe route before reusing an article.',goal:'reuse approved knowledge without treating every similar phrase as the same request',routine:'match customer intent, product or plan, version, prerequisites, permissions, stop condition, and article review status',boundary:'Never ask a customer to bypass an identity, payment, privacy, or security control to make an article fit.',example:'An article covers changing a profile email after sign-in. A locked-out customer instead follows the approved recovery route.'},
  {slug:'help-desk-customer-update-quality-check',title:'Check the quality of a help desk customer update in 60 seconds',excerpt:'Make each update say what is known, what is happening next, who owns it, and when the next checkpoint occurs.',goal:'replace vague reassurance with a useful and truthful progress update',routine:'remove unsupported timing, identify the confirmed event, name the next action and owner, and give a checkpoint the team can honor',boundary:'Do not describe an investigation, fix, or handoff as active without evidence of that state.',example:'Instead of “the team is looking into it,” the update says the billing owner accepted the review and support will check back by 16:00.'},
  {slug:'help-desk-duplicate-request-linking-routine',title:'Link duplicate help desk requests without losing customer context',excerpt:'Preserve each customer goal and communication history while coordinating shared technical work.',goal:'reduce repeated investigation without erasing request-specific ownership',routine:'verify the shared symptom, retain each affected account and customer promise, link the common investigation, and define unlink conditions',boundary:'Similar wording alone is not proof that requests share a cause, risk, or resolution.',example:'Three users report export failures on the same release. Their tickets share an investigation link but keep separate access details and confirmation steps.'},
  {slug:'help-desk-shift-start-handoff-review',title:'Review a help desk handoff at the start of a shift',excerpt:'Accept open work by checking the customer goal, evidence state, next action, due time, and escalation boundary.',goal:'make incoming ownership explicit before new queue work hides unfinished commitments',routine:'review due checkpoints first, confirm access and authority, accept actionable tickets, and return incomplete handoffs with one specific request',boundary:'Do not accept a protected decision merely because the prior shift assigned the ticket.',example:'The incoming specialist accepts a vendor follow-up but returns an account-ownership decision to the authorized manager with the missing approval named.'},
  {slug:'help-desk-sensitive-data-note-trim',title:'Trim sensitive data from help desk notes before a handoff',excerpt:'Carry the operational fact another owner needs while leaving credentials and unnecessary personal data in approved systems.',goal:'make a handoff useful without multiplying sensitive material',routine:'identify the decision needed, reference the protected record, retain only necessary context, verify access, and use the approved secure route',boundary:'Do not paste secrets, recovery codes, payment details, or full identity documents into ordinary notes.',example:'A fraud-review handoff cites the restricted case and records that identity review is pending; it does not reproduce the uploaded document.'},
  {slug:'help-desk-article-change-brief',title:'Write a change brief before editing a high-use help desk article',excerpt:'Name the trigger, affected claim, linked workflow, reviewer, rollout check, and rollback condition.',goal:'keep a small wording change from silently breaking a support routine',routine:'capture the source change, impacted steps, related macros and forms, risk owner, effective time, and post-publish sample',boundary:'Traffic and reuse make review more important, not automatic proof that the old or new wording is correct.',example:'A vendor changes its recovery screen. The editor updates the matching step and samples tickets while leaving the approval boundary unchanged.'},
  {slug:'help-desk-weekly-reopen-learning-loop',title:'Turn reopened help desk tickets into a weekly learning loop',excerpt:'Separate failed outcomes, unclear confirmation, new scope, and broken guidance before assigning a repair.',goal:'use reopen evidence to improve the right part of the service',routine:'sample reopened tickets, compare the original goal and closure basis, code the reason work resumed, and assign the smallest corrective action',boundary:'Do not rank agents by raw reopen counts without accounting for request type, policy, or customer behavior.',example:'Several tickets reopened when temporary access expired. The repair changes the closure condition and article wording, not the agents’ tone.'},
  {slug:'help-desk-after-hours-routing-check',title:'Check after-hours routing before coverage begins',excerpt:'Confirm which requests can wait, which have an on-call route, and which customer messages reflect actual coverage.',goal:'align queue behavior with the support coverage the organization can truly provide',routine:'test intake routing, priority rules, on-call contacts, fallback ownership, automated wording, and the next staffed checkpoint',boundary:'An urgent label does not grant an outsourced specialist authority outside the approved lane.',example:'A security report reaches the on-call owner, while a routine plan change receives the next staffed checkpoint rather than a false immediate-response promise.'},
  {slug:'help-desk-daily-article-publish-gate',title:'Use a daily publish gate for help desk articles',excerpt:'Publish only when a real support need, authoritative source, safe scope, owner, and maintenance trigger are present.',goal:'make daily article creation a useful operating routine instead of a volume target',routine:'compare the candidate with existing answers, failed searches, ticket language, workflow fixes, source authority, review owner, and measurable reuse event',boundary:'Do not publish a new page when the actual repair is a synonym, form field, permission, route, or ownership rule.',example:'Repeated searches for “remove former employee” reveal a missing offboarding route. The team improves navigation instead of duplicating the access policy.'}
];

function blogBody(s:BlogSeed){return [
  `The practical goal is to ${s.goal}. Start with the customer outcome and the next observable event, not a dashboard total.`,
  `Use this routine: ${s.routine}. Keep the ticket as the durable record and make every follow-up traceable to a named owner.`,
  `A useful entry separates what the customer reported, what support verified, what remains unknown, and what the current specialist is allowed to do. That separation makes outsourced coverage safer when work changes shifts or teams.`,
  `${s.boundary} When the boundary is reached, acknowledge the request, preserve permitted evidence, name the decision needed, and route it to the authorized owner.`,
  `For example: ${s.example} The customer update should reflect the same evidence state shown internally.`,
  `Review the routine with a small weekly sample. Look for missing ownership, repeated questions, bounced handoffs, stale promises, unnecessary data, and guidance that no longer matches its source. Give each finding one repair owner and follow-up date.`,
  `Published September 4, 2026 for OutsourcedHelpdeskServices.com. The measure of a good daily article is safer, clearer work in the help desk—not publication volume by itself.`
]}

export const sep04BlogArticles=blogSeeds.map(s=>({...s,published,minutes:8,heroImage:'/helpdesk-team.jpg',body:blogBody(s)}));

const sources=[
  {name:'NIST Cybersecurity Framework 2.0',url:'https://www.nist.gov/cyberframework',note:'Risk governance, roles, and accountable outcomes.'},
  {name:'NIST SP 800-53 Rev. 5',url:'https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final',note:'Control, accountability, audit, and information-protection context.'},
  {name:'ICO data minimisation guidance',url:'https://ico.org.uk/for-organisations/uk-gdpr-guidance-and-resources/data-protection-principles-a-guide-to-the-data-protection-principles/data-minimisation/',note:'Adequate, relevant, and necessary personal information.'},
  {name:'GOV.UK Service Manual: measuring user needs',url:'https://www.gov.uk/service-manual/measuring-success/measuring-user-needs',note:'Service measures grounded in user outcomes.'},
  {name:'CISA Secure by Design',url:'https://www.cisa.gov/securebydesign',note:'Security ownership and safe-default principles.'}
];

type ResearchSeed={slug:string;title:string;excerpt:string;question:string;method:string;finding:string;implication:string;limitation:string;keyStats:{value:string;label:string}[]};
const researchSeeds:ResearchSeed[]=[
  {slug:'outsourced-helpdesk-promise-aging-study',title:'Outsourced help desk promise aging: a checkpoint study',excerpt:'A bounded protocol for studying customer commitments that remain open across queue and shift changes.',question:'Which recorded events distinguish an actively managed customer promise from a commitment that is merely still visible?',method:'Define a fixed observation window, then code promise text, due time, owner, dependency, last evidence, customer update, completion condition, and outcome.',finding:'Ticket visibility alone cannot establish active control; a future checkpoint needs both an accountable owner and an observable completion event.',implication:'Measure missed checkpoints separately from ticket age and sample transfers so teams can repair ownership without changing priority definitions.',limitation:'The protocol cannot infer customer harm from delay alone, and tool timestamps may not represent acceptance or meaningful work.',keyStats:[{value:'8',label:'coded fields'},{value:'2',label:'required controls'}]},
  {slug:'outsourced-helpdesk-handoff-acceptance-evidence-study',title:'Outsourced help desk handoffs: an acceptance-evidence study',excerpt:'Examine how assignment, acknowledgement, and explicit acceptance differ when work moves between owners.',question:'What evidence shows that a receiving owner can and will perform the next action after a handoff?',method:'Sample transfers by channel and request risk; compare assignment events, requested decisions, evidence access, receiving-owner response, first action, and customer checkpoint.',finding:'Assignment is a routing event, while acceptance is evidence that the receiver understands and can own the requested next action.',implication:'Keep follow-up accountability with the sending lane until the approved acceptance event occurs, especially for protected decisions.',limitation:'Some tools infer ownership from workflow events; this study does not prescribe one universal acceptance field or escalation time.',keyStats:[{value:'6',label:'handoff signals'},{value:'3',label:'event types'}]},
  {slug:'helpdesk-knowledge-preflight-fit-research',title:'Help desk knowledge preflight: an answer-fit research protocol',excerpt:'Study whether an approved article fits the customer intent, product state, prerequisites, and authority boundary.',question:'Which preflight checks reduce unsafe or irrelevant reuse of help desk knowledge?',method:'For a fixed ticket sample, code intent, product state, version, prerequisites, permitted action, article freshness, stop condition, and final route.',finding:'Keyword similarity can find a candidate answer but cannot establish that its instructions apply to the customer’s state or permissions.',implication:'Evaluate article reuse through fit and safe-next-action evidence, not link insertion or page-view counts alone.',limitation:'A matched preflight does not prove resolution, and local product rules determine which prerequisites and permissions matter.',keyStats:[{value:'8',label:'fit checks'},{value:'1',label:'safe route'}]},
  {slug:'helpdesk-reopen-classification-reliability-study',title:'Help desk reopen classification: a reliability study',excerpt:'A repeatable method for distinguishing failed outcomes, incomplete confirmation, new scope, and guidance defects.',question:'Can reviewers consistently classify why help desk work resumed after closure?',method:'Create bounded definitions, double-code a fixed reopen sample, compare disagreements, and inspect the original goal, closure evidence, new customer evidence, and changed scope.',finding:'A reopen event is not a cause; reliable classification requires comparing the closure basis with the evidence that restarted work.',implication:'Use disagreement to improve definitions before attributing patterns to an agent, article, product, or workflow.',limitation:'Silent failures never become reopens, sample mix affects category rates, and classification cannot by itself establish causality.',keyStats:[{value:'4',label:'reason classes'},{value:'2',label:'independent reviews'}]},
  {slug:'helpdesk-daily-content-intervention-study',title:'Daily help desk content: an intervention-selection study',excerpt:'Compare new articles with edits, search improvements, form changes, routing repairs, and owner-map fixes.',question:'When repeated support demand appears, which intervention should a daily content routine select?',method:'Code repeated user goal, current answer, failed-search language, source stability, workflow friction, risk, maintenance owner, and alternative repair; predefine a follow-up measure.',finding:'Demand evidence supports investigation, but does not establish that another public article is the best intervention.',implication:'Choose the smallest maintainable repair and measure the intended operational event, such as successful discovery or a complete escalation.',limitation:'Observational demand changes by season and channel; without a comparison design, later improvement cannot be attributed solely to the selected intervention.',keyStats:[{value:'6',label:'repair options'},{value:'1',label:'follow-up measure'}]}
];

function researchBody(s:ResearchSeed){return [
  `Research question: ${s.question}`,
  `Method: ${s.method} Freeze the sample, exclusions, definitions, and observation window before reading outcomes. Keep protected artifacts in their approved system.`,
  'Evidence frame: GOV.UK guidance supports measuring whether users accomplish their goal. NIST CSF 2.0 and SP 800-53 support explicit governance, accountability, and reviewable controls; they do not define a local service level or prove a help desk outcome.',
  'Information frame: ICO data-minimisation guidance supports using personal information that is adequate, relevant, and necessary. CISA Secure by Design supports clear security ownership and safe defaults. Neither source authorizes a local access or identity decision.',
  `Finding to test: ${s.finding} Include routine, boundary, incomplete, and transferred cases so one easy path does not dominate the interpretation.`,
  `Operational implication: ${s.implication} Report counts and exceptions with their denominator and keep observed events separate from inferred causes.`,
  `Scope and limitations: ${s.limitation} Public sources provide principles rather than evidence about OutsourcedHelpdeskServices.com customers, staffing, contracts, systems, or performance.`,
  'Published September 4, 2026. This Research article defines a falsifiable review protocol; it is not a benchmark, customer study, legal opinion, or universal causal claim.'
]}

export const sep04ResearchArticles=researchSeeds.map(s=>({...s,published,sourceDate:published,hero:'/helpdesk-team.jpg',body:researchBody(s),sources,related:[]}));
