const published = '2026-09-01' as const;

type BlogSeed = {
  slug: string; title: string; excerpt: string; outcome: string; inputs: string;
  route: string; stop: string; example: string;
};

const blogSeeds: BlogSeed[] = [
  {slug:'help-desk-ticket-age-owner-review',title:'Run a ticket-age owner review without chasing every old request',excerpt:'Use age, impact, waiting reason, and ownership evidence to find work that needs a decision.',outcome:'identify aged work that has lost an accountable next action',inputs:'ticket age, customer impact, waiting party, last meaningful event, current owner, and next checkpoint',route:'continue the documented wait, reset ownership, or escalate a missing decision',stop:'Do not close work merely because it is old or silently restart a promise.',example:'A nine-day vendor wait still has an owner and Friday checkpoint, while a two-day approval request has neither; the newer ticket receives attention first.'},
  {slug:'help-desk-macro-change-review',title:'Review a help desk macro change before specialists reuse it',excerpt:'Treat saved replies as controlled guidance with sources, boundaries, and an accountable reviewer.',outcome:'decide whether changed saved language is accurate and safe for its intended queue',inputs:'macro purpose, triggering request, authoritative source, allowed audience, variables, owner, and review trigger',route:'approve the edit, narrow its scope, return it for evidence, or retire it',stop:'A macro must not imply identity verification, approval, diagnosis, or resolution that did not occur.',example:'A reset macro says access is restored after sending a link; the reviewer changes it to record delivery and request confirmation.'},
  {slug:'help-desk-customer-reply-ownership',title:'Assign ownership after a customer replies to a waiting ticket',excerpt:'Make the resumption event visible so returned work does not sit between queues.',outcome:'restore an accountable next action when new customer information arrives',inputs:'reply time, requested outcome, new facts, prior owner, queue state, risk signal, and promised checkpoint',route:'return to the prior owner, enter a bounded triage lane, or use the duty-owner path',stop:'An automated reopen event is not proof that a person accepted the work.',example:'A customer supplies the requested device ID during another shift; intake acknowledges it and routes to the named owner with a review time.'},
  {slug:'help-desk-article-retirement-check',title:'Retire a help desk article without breaking the support path',excerpt:'Remove stale guidance only after its links, macros, routes, and replacement owner are accounted for.',outcome:'withdraw unsafe or obsolete guidance while preserving a usable next route',inputs:'retirement reason, source change, inbound links, saved replies, affected queues, replacement, owner, and effective time',route:'replace, redirect readers within the article system, archive from use, or pause pending an owner',stop:'Do not leave a public alias that renders different content under the retired canonical URL.',example:'A product workflow ends; the editor removes the article from search and macros only after the replacement support route is verified.'},
  {slug:'help-desk-urgent-language-triage',title:'Triage urgent customer language without inventing severity',excerpt:'Preserve urgency as a signal while using approved evidence and ownership rules to set the route.',outcome:'respond quickly to stated urgency without converting emotion into an unsupported incident classification',inputs:'customer wording, affected outcome, scope, observed symptom, time, safety or security signals, and owner map',route:'routine priority review, protected escalation, or one route-changing clarification',stop:'Frontline urgency handling must not declare an outage, breach, or business impact the evidence does not support.',example:'“Everything is down” is recorded verbatim, then narrowed to one user unable to open a single application before routing.'},
  {slug:'help-desk-shared-inbox-handoff',title:'Create an accountable handoff from a shared help desk inbox',excerpt:'Turn an inbound message into owned work without relying on read status or forwarding alone.',outcome:'move a shared-inbox request into a trackable queue with a named next owner',inputs:'sender, requested outcome, received time, affected service, permitted identifiers, risk signals, and acknowledgement status',route:'create routine queue work, use a protected intake path, or request one bounded fact',stop:'Read receipts, labels, and forwards do not prove ownership or acceptance.',example:'A billing-access email is acknowledged, logged with minimal facts, and sent to the protected owner rather than answered from the shared inbox.'},
  {slug:'help-desk-review-sample-selection',title:'Select a useful daily help desk review sample',excerpt:'Balance routine, transferred, reopened, protected, and waiting work instead of reviewing only easy tickets.',outcome:'find workflow defects with a small repeatable sample',inputs:'queue volume, request type, owner, transfer state, reopen state, risk class, waiting reason, and review history',route:'repair coaching, source guidance, routing, access, ownership, or the sampling rule',stop:'A convenience sample cannot support claims about the entire queue.',example:'The reviewer selects two routine closures, one transfer, one reopen, and one protected stop, then reports findings as sample signals.'},
  {slug:'help-desk-next-action-wording',title:'Write a help desk next action that another owner can execute',excerpt:'Replace vague follow-up notes with an observable action, owner, condition, and checkpoint.',outcome:'make the next ticket event clear enough to accept, perform, or return with a reason',inputs:'current state, exact action or decision, accountable owner, prerequisite, evidence location, due event, and customer promise',route:'accept the action, request a missing permitted fact, or redirect to a named owner',stop:'Avoid “monitor,” “follow up,” or “investigate” unless the note says what evidence completes the action.',example:'“Follow up tomorrow” becomes “Queue lead checks vendor case 481 for a response at 14:00 UTC and updates the customer even if none arrived.”'},
  {slug:'help-desk-permission-change-intake',title:'Handle a permission-change request at help desk intake',excerpt:'Capture the requested business outcome while keeping authorization and identity decisions with approved owners.',outcome:'route access-change work without treating the requester’s message as approval',inputs:'requested outcome, affected account, role or resource, approved identity result, business owner, urgency signal, and evidence location',route:'approved routine execution, authorization review, identity exception, or security escalation',stop:'Never ask for passwords, infer entitlement, or expand access from an old ticket.',example:'A manager asks to copy a former employee’s permissions; intake records the need but routes the exact access decision to the authorized owner.'},
  {slug:'help-desk-customer-silence-checkpoint',title:'Set a truthful checkpoint when a help desk customer is silent',excerpt:'Keep waiting work accountable without treating non-response as confirmation or resolution.',outcome:'define what the queue will do when requested customer information does not arrive',inputs:'last question, why the fact matters, contact channel, elapsed time, service impact, policy window, owner, and next review',route:'send a bounded reminder, continue an approved action, retain the wait, or close under an explicit policy',stop:'Silence does not prove success, consent, or lack of impact.',example:'A customer does not confirm a delivered reset link; the desk sends one reminder and records unconfirmed completion rather than restored access.'},
  {slug:'help-desk-source-change-alert',title:'Turn a source change into a help desk article review',excerpt:'Connect authoritative product or policy changes to the exact guidance and macros they may invalidate.',outcome:'find and review every support instruction affected by a changed source',inputs:'source owner, changed claim, effective date, affected audience, linked articles, macros, forms, routes, and reviewers',route:'confirm no impact, update bounded wording, pause reuse, or retire the instruction',stop:'An alert is not proof that every linked instruction is wrong or that an unreviewed replacement is safe.',example:'An identity policy changes one approved signal; the editor pauses only the affected recovery steps and preserves unrelated guidance.'},
  {slug:'help-desk-shift-end-promise-check',title:'Check customer promises before a help desk shift ends',excerpt:'Find open commitments that need completion, transfer acceptance, or a truthful reset before coverage changes.',outcome:'leave no customer checkpoint dependent on an absent specialist',inputs:'open promises, due event, current evidence, ticket owner, receiving coverage, protected decisions, and customer channel',route:'complete the promised update, obtain handoff acceptance, or reset the commitment truthfully',stop:'Do not mark a transfer complete until the receiving owner accepts it.',example:'A specialist promised an update by 18:00 but the vendor is silent; the specialist reports that fact and obtains night-shift acceptance for the next check.'}
];

function blogBody(seed: BlogSeed) {
  return [
    `Define the operating outcome first: ${seed.outcome}. Keep the customer request visible and distinguish reported facts from support interpretation.`,
    `Collect only ${seed.inputs}. Each item should change a permitted action, route, owner, or checkpoint; exclude credentials, unrelated personal data, and speculation.`,
    `Choose among ${seed.route}. Record the condition that selected the path and the evidence another specialist can verify.`,
    `${seed.stop} The safe lane still includes acknowledgement, permitted fact gathering, approved routine work, and an honest next-update event.`,
    `Worked example: ${seed.example} The record should show the goal, evidence, next action, stop condition, owner, and customer checkpoint.`,
    `Review a small mix of routine and exception tickets after the workflow is used. Classify findings as wording, source, route, access, ownership, or boundary defects so the correct owner can repair them.`,
    `For OutsourcedHelpdeskServices.com, this Blog article was published on September 1, 2026. Success means a new specialist can take a safe, explainable next step without inheriting authority that belongs elsewhere.`
  ];
}

export const sep01BlogArticles = blogSeeds.map(seed => ({...seed, published, minutes: 8, body: blogBody(seed)}));

const sources = [
  {name:'NIST Cybersecurity Framework 2.0',url:'https://www.nist.gov/cyberframework',note:'Governance and risk-management framing.'},
  {name:'ICO data minimisation guidance',url:'https://ico.org.uk/for-organisations/uk-gdpr-guidance-and-resources/data-protection-principles-a-guide-to-the-data-protection-principles/data-minimisation/',note:'Adequate, relevant, and necessary information.'},
  {name:'GOV.UK Service Manual: user needs',url:'https://www.gov.uk/service-manual/user-research/start-by-learning-user-needs',note:'Evidence-led user-needs validation.'},
  {name:'CISA Secure by Design',url:'https://www.cisa.gov/securebydesign',note:'Security ownership and safe-default principles.'}
];

type ResearchSeed = {slug:string;title:string;excerpt:string;question:string;method:string;finding:string;implication:string;limitation:string;keyStats:{value:string;label:string}[]};
const researchSeeds: ResearchSeed[] = [
  {slug:'helpdesk-ticket-resumption-ownership-study',title:'Help desk ticket resumption ownership: a bounded workflow study',excerpt:'Examine what turns a customer reply or dependency event into accepted work.',question:'Which observable event establishes ownership when waiting work becomes actionable again?',method:'Code a fixed sample by waiting reason, resumption event, prior owner, notification, acceptance, next action, and customer checkpoint.',finding:'A status change can make work eligible without showing that any person accepted the next action.',implication:'Keep resumption and acceptance as separate events and add a duty-owner route for orphaned work.',limitation:'Tool events vary and the protocol does not measure company performance, staffing adequacy, or resolution speed.',keyStats:[{value:'7',label:'coded fields'},{value:'2',label:'distinct events'}]},
  {slug:'helpdesk-macro-evidence-study',title:'Help desk macro evidence: when saved language outruns the ticket',excerpt:'Study whether reusable replies state claims stronger than the available evidence.',question:'Where do saved replies convert an action, assumption, or pending outcome into an unsupported customer claim?',method:'Compare each selected reply with its source, trigger, required ticket evidence, variables, stop condition, and final claim.',finding:'The highest-risk mismatch occurs when a macro states an outcome although the ticket proves only that an action was attempted.',implication:'Map every outcome claim to a required evidence field and name the reviewer for source changes.',limitation:'A bounded sample cannot establish queue-wide prevalence, customer harm, or universal wording rules.',keyStats:[{value:'6',label:'review elements'},{value:'1',label:'claim-evidence map'}]},
  {slug:'helpdesk-aging-accountability-study',title:'Help desk ticket aging: accountability signals beyond elapsed time',excerpt:'Compare age with ownership, waiting condition, risk, and promised checkpoints.',question:'Which signals distinguish legitimately waiting tickets from old work that has lost accountability?',method:'Stratify a fixed sample by age, then code impact, waiting party, resumption condition, owner, acceptance, last event, and checkpoint.',finding:'Elapsed time alone cannot separate a controlled dependency from abandoned work; ownership and a review event can.',implication:'Use age as a review trigger, then decide from the waiting condition, owner evidence, risk, and customer promise.',limitation:'The protocol does not define service levels or prove that older tickets are more harmful.',keyStats:[{value:'8',label:'accountability fields'},{value:'1',label:'age trigger'}]},
  {slug:'helpdesk-article-retirement-dependency-study',title:'Help desk article retirement: a dependency-mapping study',excerpt:'Trace the routes, macros, forms, and links that can keep retired guidance alive.',question:'Which dependencies must be checked before an obsolete help desk article leaves active use?',method:'Map selected articles to authoritative sources, search results, inbound links, macros, forms, queue routes, audiences, and owners.',finding:'Removing a page does not retire its instructions when copied language and operational dependencies remain active.',implication:'Require a dependency register, replacement decision, effective time, and verification sample for retirement.',limitation:'Informal copies may remain undiscovered, and dependency counts do not establish risk without context.',keyStats:[{value:'8',label:'dependency classes'},{value:'4',label:'retirement gates'}]},
  {slug:'helpdesk-promise-transfer-study',title:'Help desk customer promises across shifts: a transfer-evidence study',excerpt:'Examine whether update commitments survive a change in specialist or coverage window.',question:'What evidence shows that a customer promise remains owned after a shift or queue transfer?',method:'Review a fixed sample for promise wording, due event, evidence state, sending owner, receiving owner, acceptance, update, and reset reason.',finding:'Ticket assignment preserves a destination but not necessarily the commitment, due event, or accepted responsibility.',implication:'Transfer the exact promise with its evidence state and require acceptance or a truthful reset before the due event.',limitation:'The study cannot establish customer satisfaction, staffing sufficiency, or a universally appropriate update cadence.',keyStats:[{value:'8',label:'promise fields'},{value:'3',label:'transfer outcomes'}]}
];

function researchBody(seed: ResearchSeed) {
  return [
    `Research question: ${seed.question}`,
    `Methodology: ${seed.method} Freeze the inclusion rule and observation window before reviewing outcomes, and keep restricted artifacts in approved systems.`,
    'User-needs frame: GOV.UK guidance supports learning what users are trying to accomplish and validating needs with evidence. The requested outcome therefore remains distinct from an internal queue label.',
    'Governance frame: NIST CSF 2.0 supports explicit risk governance and accountable decisions. It does not establish a local permission, service level, or result.',
    'Information boundary: ICO data-minimisation guidance supports using information that is adequate, relevant, and necessary. More transcript or screenshot data is not automatically better evidence.',
    `Primary finding: ${seed.finding} Test the interpretation against a routine case, near-neighbor, incomplete case, and protected case.`,
    `Operational implication: ${seed.implication} Frontline specialists can preserve goals, gather permitted facts, follow approved steps, and communicate checkpoints while protected decisions remain with authorized owners.`,
    'Security implication: CISA Secure by Design supports security ownership and safe defaults. Explicit stops and accountable routes are preferable to improvised workarounds.',
    `Limitations: ${seed.limitation} Public sources supply principles, not evidence about OutsourcedHelpdeskServices.com customers, contracts, credentials, staffing, or outcomes.`,
    'Published September 1, 2026: this Research release provides a bounded review protocol, not a performance benchmark or universal causal claim.'
  ];
}

export const sep01ResearchArticles = researchSeeds.map(seed => ({...seed, published, sourceDate: published, hero:'/helpdesk-team.jpg', body:researchBody(seed), sources, related:[]}));
